export const catBreeds = [
    {
        "name": "Abyssinian",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Abyssinians are friendly, curious creatures who always want to get in on the fun. They love to play and have energy to expend. They are loyal and loving but are by no means a lap cat. The Abyssinian cat breed enjoys spending time with their owners, shadowing them around the house."
    },
    {
        "name": "American Bobtail",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The American Bobtail cat might look like a wild cat, but don’t let that fool you—they are fully domesticated sweet, loving, and smart cats that enjoy being with their owners. They are self-assured, outgoing, and adaptable cats that do well in most homes. They are not as chatty as other breeds but aren’t afraid to use their voices. Playful and full of energy, they will ask for your attention by meowing or jumping in your lap."
    },
    {
        "name": "American Curl",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "People-first cats, the American Curl is attentive and affectionate without being harassing. They love perching to watch their families and love playtime of any sort. They have typical cat curiosity but aren’t as mischievous as other breeds."
    },
    {
        "name": "American Ringtail",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "American Shorthair",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Easygoing and adaptable, the American Shorthair cat is a good companion cat. They love attention but are independent. They are more inclined to sit next to you than to be on top of you. Quiet and balanced, they are calm cats and thrive in similar environments."
    },
    {
        "name": "American Wirehair",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Playful and energetic, the American Wirehair cat breed is a charming companion with a humorous flair. They enjoy cuddle time and interactive play, and their gentle and quiet nature makes them delightful housemates."
    },
    {
        "name": "Applehead Siamese",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Incredibly affectionate, intelligent, and opinionated, the Siamese is a friend to everyone. They can talk a mile a minute in their signature, low-pitched voice, making them known as the extroverts of the feline world. Siamese have a very dependent nature, often bonding very closely to one person, desiring to be around them constantly. If you go into the kitchen to cook, they will want to follow you and get in on the action!  Siamese cats are self-assured and highly active. They need daily playtime with their owners—or else they’ll find something to occupy their time. Siamese should not be left alone for long periods, as they need to be with people and can develop separation anxiety if not regularly around their owners, but they can be left for a few hours at a time. They require a lot of attention and affection but will give you back every ounce of love you give them."
    },
    {
        "name": "Asian",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Asian Semi-longhair",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Australian Mist",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Balinese",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Balinese cats are smart, playful, and love to be the center of attention. These chatty kitties will keep you entertained with their antics and endless curiosity. While they're affectionate and love to cuddle, they also need plenty of playtime and mental stimulation. Don't be surprised if they find creative ways to keep themselves busy, like exploring every nook and cranny of your home."
    },
    {
        "name": "Bambino",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Bengal",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "The Bengal is born an entertainer. Known for their bold personality and playfulness, they love to learn new things and can even be trained to perform tricks. Don’t let the wildcat appearance fool you—Bengals are friendly, full of life, and love people. They are clever, athletic, and curious, and make fantastic pets for experienced cat owners."
    },
    {
        "name": "Birman",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Loving, gentle, and supremely playful, Birman cats are faithful companion cats that love to shadow their owners. They adore being adored, perhaps thanks to a long history as a temple cat in Burma (Myanmar). Intelligent and people-oriented, they are curious around strangers. They are generally easy cats to care for."
    },
    {
        "name": "Bombay",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Bombays are anything but your stereotypical aloof feline. They are social butterflies with a bit of a mischievous streak. Highly people-oriented, they crave attention and won't hesitate to use their mesmerizing copper eyes to get their point across or follow you around the house as your four-legged shadow. While they make for a loving and interactive companion, just prepared for their clever antics—they'll invent their own entertainment if left to their own devices."
    },
    {
        "name": "Brazilian Shorthair",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Bristol",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "British Longhair",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "British Shorthair",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "For classic cat antics, look to the British Shorthair cat. They’ll steal your jewelry, jump off your tables, and then come running to you for affection. They are attention hogs but aren’t constantly underfoot and often keep a low profile, playful but not excessively so. Quiet, even-tempered, and British in demeanor, they can be aloof with strangers. With owners, however, they are faithful and devoted companion cats, always seeking love and attention. The more you give to them, the more they give back. These confident and calm cats do have a mischievous streak, but for the most part, are happy just to be near their owners and observe whatever they are doing. They tend to love on an entire family, not just one person and can be more independent than other cat breeds despite loving the spotlight. British Blues are not vocal cats and squeak rather than meow. However, their purrs are some of the loudest, resembling motorboats."
    },
    {
        "name": "Burmese",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Burmese cats are known for their affectionate and playful personalities. Intelligent and curious, they thrive on human interaction and enjoy being the center of attention. While both males and females exhibit loving and devoted behavior, females tend to be more spirited and emotionally expressive, while males are slightly calmer and more laid-back. Their unique vocalizations add to their charm, though they are not overly talkative unless they have something important to communicate."
    },
    {
        "name": "Burmilla",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The Burmilla’s personality mixes the best traits of its parents, the Burmese and Chinchilla Persian. These intelligent and playful cats are known for their adventurous spirit and love of human interaction. They’re also known to retain their kitten-like energy well into adulthood. Although playful, they also have a calm and affectionate side, enjoying cuddles and lap time. Their curiosity and mischievous tendencies also keep things interesting."
    },
    {
        "name": "Calico",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Keep in mind that because Calico cats are a type and not a breed, there’s a wide variety of personality types within the cats. Many are playful, engaging, and spunky. Calico cats can often be strong-willed. They can be vocal and independent, but affectionate and loving, too."
    },
    {
        "name": "California Spangled",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Canadian Hairless",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Celtic Shorthair",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Chantilly-Tiffany",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Chartreux",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Chartreux cats are great companion cats that purr and chirp rather than meow. They have curious smiles and are loyal, loving, and adaptable. More the strong and silent type, they generally keep to themselves despite having a good sense of humor and enjoying family life. They are smart and learn quickly."
    },
    {
        "name": "Chausie",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Chartreux cats are great companion cats that purr and chirp rather than meow. They have curious smiles and are loyal, loving, and adaptable. More the strong and silent type, they generally keep to themselves despite having a good sense of humor and enjoying family life. They are smart and learn quickly."
    },
    {
        "name": "Cheetoh",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Chinchilla",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The Burmilla’s personality mixes the best traits of its parents, the Burmese and Chinchilla Persian. These intelligent and playful cats are known for their adventurous spirit and love of human interaction. They’re also known to retain their kitten-like energy well into adulthood. Although playful, they also have a calm and affectionate side, enjoying cuddles and lap time. Their curiosity and mischievous tendencies also keep things interesting."
    },
    {
        "name": "Colorpoint Shorthair",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Cornish Rex",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Cornish Rex cats are playful, intelligent, and endlessly curious. With their athletic build and boundless energy, they resemble playful kittens well into adulthood. These sociable and affectionate felines thrive on human interaction and often form strong bonds with their owners. Inquisitive by nature, they love to explore every nook and cranny, and their playful antics can be both entertaining and challenging. While known for their gentle and loving demeanor, Cornish Rexes also have a mischievous side, with a penchant for stealing food and climbing to unreachable heights."
    },
    {
        "name": "Cuban Cat",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Cymric",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Cymric cats are known for their gentle and playful personalities. While they can be independent, they also crave attention and affection from their humans. Unlike many other cats, Cymrics love to play in water. They also have a knack for jumping to unexpected heights, but despite their athleticism, Cymrics are typically calm and relaxed, making them suitable companions for families with children."
    },
    {
        "name": "Cyprus",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Desert Lynx",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Devon Rex",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "Devon Rex cats are high-energy, curious creatures. They love being involved in everything and will follow you from room to room, expecting to be part of the action. While not overly vocal, they'll let you know when they want attention. Intelligent and active, they need plenty of playtime and mental stimulation."
    },
    {
        "name": "Dilute Calico",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Keep in mind that because Calico cats are a type and not a breed, there’s a wide variety of personality types within the cats. Many are playful, engaging, and spunky. Calico cats can often be strong-willed. They can be vocal and independent, but affectionate and loving, too."
    },
    {
        "name": "Dilute Tortoiseshell",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Domestic Long Hair",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Because the Domestic Long Hair cat is a type and not a breed, there is a lot of variety in the cat’s personality, ranging from cuddly to independent and from hyperactive to mellow. Most tend to be playful and eager, though, and are generally highly adaptable."
    },
    {
        "name": "Domestic Medium Hair",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Domestic Medium Hair cats have a range of personality traits. Some crave alone time while others will nudge you all day long, looking for scratches. They can be playful or more reserved, although most are generally friendly and easygoing."
    },
    {
        "name": "Domestic Short Hair",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The personality of the Domestic Shorthair cat is as varied as the cat’s coat. They can be playful and vocal or calm and quiet. Regardless of personality, though, they are sociable and outgoing cats who thrive off of human interaction. They are energetic and smart and need owners who can invest time in meeting their enrichment needs. Once mentally exhausted, they’ll enjoy nothing more than sunbathing on a shelf or in front of a window."
    },
    {
        "name": "Dwelf",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Dwelf Variant",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Egyptian Mau",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "European Burmese",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Exotic Shorthair",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Exotic Shorthair cats are an American Shorthair and Persian mix. They are playful, love lounging, and can be mellow like a Persian but also lively. Laidback, loyal, and affectionate, they have an entertaining streak that might see them up for a game of chasing a catnip mouse. They love being involved in their owner’s life, following them from room to room to get in on the action. Affection is lavished on their owners through purrs and licks and they hope for it to be reciprocated in the form of hugs and cuddles."
    },
    {
        "name": "Extra-Toes Cat / Hemingway Polydactyl",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Foldex",
        "activity": "high",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "German Rex",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Havana",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Small in size but large in personality, the Havana Brown cat is a confident, self-assured, and intelligent cat. They are loving and gentle and have a reputation for being puppy-like. They love to paw at their owners affectionately and enjoy interacting with them and playing games like fetch. They are successful cat burglars; if something goes missing in your house, your Havana Brown cat almost certainly has taken it back to their bed for further inspection."
    },
    {
        "name": "Havana Brown",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Highlander",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Himalayan",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Sweet and even-keeled, the Himalayan cat is a chill companion. They love to play and can engage in games like fetch. They are devoted and loyal cats that love to be groomed and cuddled. They are loving without being clingy and are not particularly vocal, unlike the related Siamese Cat. Sometimes they are called “Himmies.”"
    },
    {
        "name": "Himalayan Variant",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Japanese Bobtail",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Playful and inquisitive, Japanese Bobtail cats love to engage with their owners. They love to be fawned over and cuddled and can spend their days climbing and playing. They’re human-oriented and get along well with other cats if introduced carefully."
    },
    {
        "name": "Javanese",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "Similar to the Balinese cat, the Javanese cat is affectionate and cheerful. They want to be around their owners, chatting to them in an endless stream of cat commentary. Inquisitive, smart, and good communicators, they are responsive and engaging cats who seem to understand every word their owners say. They’re eager learners, making them easy to train."
    },
    {
        "name": "Khao Manee",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Kinkalow",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Korat",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Perhaps more curious than your typical cat, Korat cats stay on the move and adore exploring new spaces. This breed is quick learners who enjoy playing with interactive toys to keep their intelligent minds busy. They’re also big cuddle bugs, sure to show their family lots of affection as well as loyalty."
    },
    {
        "name": "Kurilian Bobtail",
        "activity": "high",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Lambkin",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "LaPerm",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The LaPerm cat breed is a charming blend of elegance and friendliness. Known for their easy going nature, LaPerms appreciate playtime and can even learn tricks. Though playful, they prefer a calmer environment and are not overly boisterous."
    },
    {
        "name": "Lykoi",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Maine Coon",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "These chatty companions are America’s second-most popular breed for a reason—they dole out love and affection in spades. Devoted to their families and incredibly intelligent, these cats are basically kittens in big catsuits. Gentle giants who are playful well into old age, Maine Coons are clever and form strong bonds with their households. Most want to be near you but not on your lap. Maine Coons are true family members and participate in all family routines, whether watching you channel surf from the comfort of the couch or following you from room to room. As befits a former seafarer, Maine Coons are fascinated by water, perhaps because their thick coats are water-repellent and won’t become annoyingly soaked as easily as a thinner coat would. Some will join their humans in the shower briefly, or at least walk around on the wet floor after you get out. They prefer to stand on the edge of the tub, however, and touch the water with a curious paw."
    },
    {
        "name": "Manx",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Manx cats are social and gregarious furry friends who are gentle and affectionate with people and pets they know. They can be aloof with strangers. They are strongly devoted and loyal to their families. Highly intelligent, playful, and fun to have around the whole family, they can make great family pets, even with smaller children. Manx cats have a strong fascination with water, but by no means do they want to get wet—they just might splash and make a bit of a mess. They also love to climb and are skilled jumpers thanks to their powerful, rounded hind legs."
    },
    {
        "name": "Mekong Bobtail",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Minuet",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Munchkin",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Short on legs but big on personality, the Munchkin cat is friendly with a big heart. They are self-assured and outgoing and make devoted companion cats. They get along well with other cats, dogs, and people, and love to be playful, especially wrestling with other cats. Fast and slightly clumsy, taking corners like a toddler learning to walk, they often will sit up on their haunches like a prairie dog. Their only challenge is a vertical one; they can’t jump. Like your friend who just can’t quit estate sales, Munchkins are collectors, borrowing small shiny objects and stashing them away for rainy day play."
    },
    {
        "name": "Napoleon",
        "activity": "high",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Nebelung",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "While gentle Nebelung cats are shy and slightly aloof with strangers, they are loyal, loving, and deeply affectionate with their family and well-known friends. Once Nebelungs form close bonds of love and trust, they maintain them for life. This breed adores human company and will want to be your shadow, following you wherever you go, always eager to get in on the action. Nebelungs make excellent lap cats and can be demanding when they want to cuddle."
    },
    {
        "name": "Norwegian Forest",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Norwegian Forest Cat",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Ocicat",
        "activity": "high",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Intelligent, active, and a social butterfly, the Ocicat has a big personality. They love being up to date on family activities and the social calendar and can even seem dog-like in their eagerness. Great “supervisors,” they like to follow their family members around the house, shadowing them. Like a gymnast, Ocicats can jump high and balance on narrow ledges, although it’s up to you whether or not you want to give them a gold medal for doing so. While sweet and inquisitive, Ocicats can be high energy and demanding of owner attention, so they do best with owners who can devote a lot of time and energy to them."
    },
    {
        "name": "Oriental",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Oriental Bicolor",
        "activity": "high",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Oriental Long Hair",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Energetic, animated, and yes, mischievous, the Oriental Shorthair cat loves the spotlight. They like nothing more than to be the center of attention and will demand owners treat them as such. They crave play and will do anything to get an owner engaged in it, including knocking things over and making their presence known. Social, loyal, and affectionate, they are sensitive and get their feelings hurt easily. They often bond strongly with one person."
    },
    {
        "name": "Oriental Longhair",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Oriental Short Hair",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Energetic, animated, and yes, mischievous, the Oriental Shorthair cat loves the spotlight. They like nothing more than to be the center of attention and will demand owners treat them as such. They crave play and will do anything to get an owner engaged in it, including knocking things over and making their presence known. Social, loyal, and affectionate, they are sensitive and get their feelings hurt easily. They often bond strongly with one person."
    },
    {
        "name": "Oriental Tabby",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Persian",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Less life of the party and more stay-at-home and read, the Persian is a sweet, placid, and even-tempered cat. They enjoy regally lounging about, observing their owners, and getting in small bursts of energy through gentle games. They are intelligent but not as curious as some other cat breeds and are fiercely devoted to their humans, albeit selective in bestowing that honor on them. Trust and love must be earned, but once they are, they bond strongly. They crave attention and love being fussed over like a newborn baby but won’t beg for it like other breeds will."
    },
    {
        "name": "Peterbald",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Pixiebob",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The adaptable Pixie-Bob cat can range from being highly sociable to more reserved, but they all share a common love for their human companions. They’re highly intelligent and can learn tricks and commands, making them even more engaging and fun to be around. While they can be vocal at times, their communication style is typically gentle and melodic."
    },
    {
        "name": "Raas",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Ragamuffin",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Lovable Ragamuffin cats are the ultimate cuddle companions, known for going limp in your arms like a plush toy. They might not be the most energetic cats, but they adore playing with their favorite people and will even fetch a tossed toy before snuggling up in your lap for some quality cuddle time. These furballs greet you at the door and follow you like a shadow, ensuring they never miss a moment of your day.While they’re not big talkers, Ragamuffins know how to make their voices heard when it matters—especially if their food dish is empty. They’re easygoing and adaptable, fitting into all kinds of households and environments. Whether it’s other cats, dogs, or well-behaved kids, Ragamuffins are generally great at getting along with everyone."
    },
    {
        "name": "Ragdoll",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Ragdoll Variant",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Russian Blue",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Befitting their regal-looking coat, Russian Blues are genteel, quiet, and calm cats that love to be affectionate and playful with their families. You won’t have issues with Russian Blues batting things off your counter or getting up to classic cat behavior—they are generally well-mannered and trainable. A slight upturn at the corners of their mouths makes them look like they are smiling.  They will hide if a home gets too chaotic with visitors. They are somewhat active cats, preferring to pounce on toys and bat at sunbeams rather than get up to cat mischief. Able to entertain themselves and be left alone for periods, they prefer their humans to be home so they can follow them around.  Routine fuels them, especially when it comes to feeding time."
    },
    {
        "name": "Russian White",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Savannah",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Scottish Fold",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Sweet, adaptable, friendly, and not too demanding of their owners, Scottish Fold cats make excellent pets. They have primary attachments to their chosen humans, although they do get along well with strangers and other humans. They love attention but on their own terms, and won’t seek it from owners incessantly. They’re devoted without being clingy and prefer to be near you rather than on top of you. They love string games and the thrill of the chase.  Their folder ears are expressive and will turn to listen to you, lay back in anger, or prick up when they hear food being dispensed. The fold will become less pronounced if the cat is sick or upset."
    },
    {
        "name": "Scottish Straight",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Selkirk Rex",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Selkirk Rex cats are beloved for their sweet and affectionate personalities. These cuddly companions love spending time with their humans and are often described as \"teddy bear\" cats due to their soft, curly coats and gentle nature."
    },
    {
        "name": "Serengeti",
        "activity": "high",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Siamese",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Incredibly affectionate, intelligent, and opinionated, the Siamese is a friend to everyone. They can talk a mile a minute in their signature, low-pitched voice, making them known as the extroverts of the feline world. Siamese have a very dependent nature, often bonding very closely to one person, desiring to be around them constantly. If you go into the kitchen to cook, they will want to follow you and get in on the action!  Siamese cats are self-assured and highly active. They need daily playtime with their owners—or else they’ll find something to occupy their time. Siamese should not be left alone for long periods, as they need to be with people and can develop separation anxiety if not regularly around their owners, but they can be left for a few hours at a time. They require a lot of attention and affection but will give you back every ounce of love you give them."
    },
    {
        "name": "Siberian",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Siberians are often seen as the perfect cat: They can be left alone for small periods and can sufficiently entertain themselves as long as they are given the means to do so, and they are super affectionate, enjoy being handled, and love being around people.Adept at problem-solving, they are expressive and use quiet meows, trills, chirps, and a lot of purring to talk to their owners. They’ll meet you at the door when you come home to tell you about their day—and will want to hear about yours.They are fascinated with water, often dropping toys into their water dishes or investigating bathtubs before they’re dry. This is a cat that will want to be near you when you shower, often walking on the edge of the tub to dip a curious paw into the water to play."
    },
    {
        "name": "Silver",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Singapura",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The Singapura cat is a mischievous and outgoing feline with large, expressive eyes. Known for their inquisitive nature, they love to be involved in their human's activities. Singapuras are undeniably playful. Their friendly and affectionate nature makes them wonderful companions for families, but they thrive in calmer environments."
    },
    {
        "name": "Skookum",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Snowshoe",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Snowshoe cats have outgoing and friendly personalities. They’re intelligent and curious, often engaging in playful antics and learning new tricks. While they can be affectionate and love bonding with their humans, they also have an independent side. Their love for water and tendency to \"borrow\" small objects add to their charming and mischievous nature."
    },
    {
        "name": "Sokoke",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Somali",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Somali cats are animated, funny, and playful cats that often get up to no good. They love to play fetch, dissect things, bite, chase, and stay very active, hinting at their ancestry as wild African cats. These high-spirited cats have soft voices, active minds, and voracious appetites. Determined and stubborn, they like to see their cat ideas through, even if that means knocking something off the kitchen cabinet at 4 am. They’re not cuddlers and prefer to be near, not on top of, their owners. They show love by being involved in every aspect of an owner’s life—if you open a drawer to look for something, chances are their paws will be right there with your hands."
    },
    {
        "name": "Sphynx",
        "activity": "medium",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "Lively, alert, and downright naughty sometimes, the Sphynx Cat can perform aerialist feats. They’re devoted to their families and love following humans around, although sometimes it’s for the sole purpose of being nosy. They are curious and love to demand attention, akin to a small toddler. (They don’t like to compete with human toddlers for attention.) Despite looking otherworldly, they are still cats, charming and mysterious to a fault."
    },
    {
        "name": "Sphynx / Hairless Cat",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Lively, alert, and downright naughty sometimes, the Sphynx Cat can perform aerialist feats. They’re devoted to their families and love following humans around, although sometimes it’s for the sole purpose of being nosy. They are curious and love to demand attention, akin to a small toddler. (They don’t like to compete with human toddlers for attention.) Despite looking otherworldly, they are still cats, charming and mysterious to a fault."
    },
    {
        "name": "Suphalak",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Tabby",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Tennessee Rex",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Texas Rex",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Thai",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Tiffany",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Tiger",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Lively and sociable, Toyger cats are often described as \"dog-like\" in their playful behavior. Their intelligent nature makes them entertaining companions, always eager for a game or a cuddle. They also possess a confident and independent streak and aren’t afraid to voice their opinions, whether it's through playful antics or vocalizations."
    },
    {
        "name": "Tonkinese",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Tonkinese cats are a captivating blend of intelligence and charm. They love conversation. Expect witty banter and lively chats from your feline friend. These dynamic cats crave human interaction and are often described as \"dog-like\" in their devotion. They'll follow you from room to room. When they’re not exploring their territory or engaging in high-spirited antics, Tonkinese cats enjoy the comfort of a cozy lap."
    },
    {
        "name": "Torbie",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Tortoiseshell",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Toyger",
        "activity": "medium",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Lively and sociable, Toyger cats are often described as \"dog-like\" in their playful behavior. Their intelligent nature makes them entertaining companions, always eager for a game or a cuddle. They also possess a confident and independent streak and aren’t afraid to voice their opinions, whether it's through playful antics or vocalizations."
    },
    {
        "name": "Turkish Angora",
        "activity": "high",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Turkish Angora cats can be vocal and love chatting with their owners. Sweet but often relentless in their pursuit of play and attention, they can be stubborn. They’re unable to sit still until their enrichment needs have been met. When bored or trying to get your attention, they’ll do things like turn on faucets or knock things off shelves. Some Turkish Angora cats love to swim."
    },
    {
        "name": "Turkish Van",
        "activity": "low",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "quiet",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Turkish Van cats are beautiful bundles of energy with a splash of personality. Known for their love of water and playful antics, these cats are anything but ordinary. They're intelligent, crave attention, and form incredibly strong bonds with their favorite people. They're always on the move, exploring their environment with fearless curiosity."
    },
    {
        "name": "Turkish Vankedisi",
        "activity": "low",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": false,
        "talkative": "chatty",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": null
    },
    {
        "name": "Tuxedo",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "Ukrainian Levkoy",
        "activity": "high",
        "sheds": "little",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "quiet",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "York Chocolate",
        "activity": "high",
        "sheds": "lot",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": null
    },
    {
        "name": "York Rex",
        "activity": "low",
        "sheds": "none",
        "trainability": "",
        "barks": "",
        "affectionate": true,
        "talkative": "chatty",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": null
    }
];