export const dogBreeds = [
    {
        "name": "Afghan Hound",
        "activity": "low",
        "sheds": "lot",
        "trainability": "difficult",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "While the Afghan Hound looks glamorous, they were originally bred to chase down game over the rough terrain of Afghanistan. They are well-mannered indoors, but once on the scent of something outside might not be able to shake it. While good with kids, they are not considered especially playful or affectionate, although they are devoted. Sensitive and independent, they can sometimes be aloof and reserved, especially with strangers. With family, they are happy-go-lucky and silly."
    },
    {
        "name": "Airedale Terrier",
        "activity": "medium",
        "sheds": "none",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Confident and bold Airedale Terriers share the common terrier traits of loyalty, friendliness, and boundless curiosity. Their playful spirit and seemingly endless energy make them enthusiastic companions, always eager for adventure. Airedales are fiercely devoted to their family and possess a strong protective streak. However, while generally friendly, they can be reserved with strangers and may not take kindly to unknown dogs."
    },
    {
        "name": "Akita",
        "activity": "high",
        "sheds": "none",
        "trainability": "easy",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The Akita is a bold dog: independent, stubborn, and tenacious with a soft side reserved for their owners. They can be reserved or domineering with strangers, requiring a careful introduction to new dogs and household pets."
    },
    {
        "name": "Alaskan Malamute",
        "activity": "high",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "These powerful pups are playful goofballs with a stubborn streak. They love their families but skip their daily walk and they might unleash their inner howling instinct in protest. Friendly with familiar faces, Malamutes might need a proper introduction to new furry friends to avoid a bossy attitude. They can be cuddly comedians, despite their imposing stature."
    },
    {
        "name": "American Bulldog",
        "activity": "high",
        "sheds": "little",
        "trainability": "medium",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "A well-trained, socialized American Bulldog should be friendly, enjoy playtime, and get along well with the entire family. This breed has a natural pep in its step and a bouncy demeanor. With the right owner and training, the American Bulldog breed can be humorous and adorable. Due to their size, they can often be clumsy, especially as a puppy.  American Bulldogs are extremely sensitive but with the right training, confidence, and love, they make loyal and devoted pets."
    },
    {
        "name": "American Eskimo Dog",
        "activity": "medium",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The definition of “bright-eyed and bushy-tailed,” the American Eskimo Dog is a fun-loving and easygoing dog. They can be independent and tenacious, though, hinting at their Spitz origins. Calm and polite indoors, they are ready to play and run once outside. Originally bred as watchdogs, they can be reserved around strangers."
    },
    {
        "name": "American Foxhound",
        "activity": "high",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The American Foxhound is a keen and outgoing dog that’s ready to work at the drop of a hat. They love their families and being part of a pack. They are tolerant, gentle, and affectionate without being overly fawning. Exercise is important to make them well-mannered dogs, as is training. They do have a typical hound mentality in that if they find a scent they like, they won’t shake it—not even if their owner asks them to. They can be reserved with strangers."
    },
    {
        "name": "American Staffordshire Terrier",
        "activity": "high",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Lovey-dovey and calm with their families, the American Staffordshire Terrier is a generally friendly dog. They can be comically enthusiastic and love nothing more than being with their family, receiving attention, and giving affection. They have unfortunately been the victims of stigma and branded as dogs to fear when in reality they are sweet-natured."
    },
    {
        "name": "Australian Shepherd",
        "activity": "medium",
        "sheds": "none",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "With a hardworking spirit and grit, the Australian Shepherd is the epitome of the American West, the place where they first became popular in this country. They were originally bred to drive and herd. Suspicious of strangers but immensely devoted to their families, the Aussie Shepherd dog gets along well with other animals and children if socialized early and often. They love having a job to do, especially on a working farm. They are loving, alert, confident, independent, affectionate, and extremely smart dogs. The Aussie dog learns quickly—and that could include bad habits! It can take a lot to exhaust these dogs properly, and a bored Aussie can be a vocal and mischievous one."
    },
    {
        "name": "Basenji",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "Imagine a cat-like dog: the Basenji is a clever, stubborn, independent, and reserved breed. They love to chase and trail like a cat and regular mental and physical stimulation is a must. Instead of barking they yodel, howl, shriek, and occasionally let out a quirky-sounding \"fox bark.\" While they get along well with other dogs, they don’t always warm to other Basenjis."
    },
    {
        "name": "Basset Hound",
        "activity": "high",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "While they might look serious on the surface, the Basset Hound is a social butterfly with the manners of an English gentleman. They are affectionate with their families and can be reserved with strangers, albeit always polite. They love children and get along with other dogs and animals. They crave companionship and cannot be left alone."
    },
    {
        "name": "Beagle",
        "activity": "low",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Beagles are bold dogs who pack a hefty punch of personality for their size. Their happy, go-lucky, adventurous demeanor makes them full of life and pizzazz. They are highly active, affectionate, and cheerful dogs who love being involved with their owners.  Developed as pack animals, Beagles love being around others and crave companionship from humans and other dogs. They are great watchdogs who are vocal and will bark or howl at anything unusual and let you know when something is off. However, if a stranger offers them food or playtime, this all goes out the window! They are extremely food-motivated and can get especially vocal around dinnertime.  A naturally curious breed that loves to explore the outdoors, Beagles have an enthusiastic way of approaching life making them entertaining and enjoyable to be around."
    },
    {
        "name": "Belgian Shepherd / Laekenois",
        "activity": "high",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "You can probably picture a Belgian Laekenois protecting a flock, as they are the quintessential herding and guarding dog. Think of them as honors students: independent thinkers who are eager to learn and please and get an A+ in the process. Affectionate, loyal, and curious, they can be introverted around strangers and might take some time to warm up to people they don’t know. They are often seen as the “softest” of the four Belgian Shepherds, cuddly and friendly."
    },
    {
        "name": "Belgian Shepherd / Malinois",
        "activity": "high",
        "sheds": "little",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Belgian Malinois are working dogs that thrive on having a job to do and constant mental and physical stimulation. This is a high-energy and intense breed. These dogs are alert, smart, and serious. They can be aloof with strangers and should be introduced to other dogs and animals carefully. Some can be domineering. When confined, they often run in sweeping circles in an effort to stay on the move. They are protective of their home and family."
    },
    {
        "name": "Belgian Shepherd / Sheepdog",
        "activity": "high",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Belgian Malinois are working dogs that thrive on having a job to do and constant mental and physical stimulation. This is a high-energy and intense breed. These dogs are alert, smart, and serious. They can be aloof with strangers and should be introduced to other dogs and animals carefully. Some can be domineering. When confined, they often run in sweeping circles in an effort to stay on the move. They are protective of their home and family."
    },
    {
        "name": "Belgian Shepherd / Tervuren",
        "activity": "high",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "A Belgian Tervuren dog is as sharp as its gaze. They are natural herders and guarders. Unlike their more intense Belgian Shepherd cousins, the Tervueren breed possesses a remarkable ability to unwind and enjoy life's simpler pleasures after a hard day’s work. Initially icy with strangers, they thaw into loyal companions given time and trust. With family, they’re affectionate and protective, forming deep bonds, especially with respectful children."
    },
    {
        "name": "Bichon Frise",
        "activity": "medium",
        "sheds": "little",
        "trainability": "easy",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "Like your friend who keeps asking you to work out at 5 am, the Bichon is eager, perky, and full of energy. They are endearing companions to humans and other pets alike and are very good with children. Sensitive little souls who want to please their owners, are responsive and alert, always looking for an opportunity to play. They don’t like to be alone and could bark excessively if they are."
    },
    {
        "name": "Bloodhound",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "While calm companions in a home, Bloodhounds are tireless once on a scent. Tough, stubborn, and independent, they can also be gentle, placid, and trustworthy, especially around children, although they might be too serious and not playful enough for some kids. They are not lazy hound dogs by any stretch of the imagination, but rather active, instinctual hard workers. They aren’t the easiest dogs to train for obedience but pick up trailing tasks easily and with gusto."
    },
    {
        "name": "Bluetick Coonhound",
        "activity": "low",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The Bluetick Coonhound is friendly and full of gusto, ready for any adventure. They can be headstrong and independent, especially when focused on a scent. They are known to jump and to weasel their way through gates and fences, all in pursuit of chasing a scent down. Affable and easygoing, there’s no such thing as a stranger to them. When excited they bay—loudly."
    },
    {
        "name": "Border Collie",
        "activity": "low",
        "sheds": "none",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Every Border Collie is a shepherd at heart, constantly on the lookout for things to round up. No toy is safe from being gathered! These active workers are intelligent and attentive, and they have incredible agility with the ability to change directions on a dime. They can sometimes be considered workaholics since it’s so ingrained in them to be alert at all times."
    },
    {
        "name": "Boykin Spaniel",
        "activity": "low",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Friendly, happy, and eager, the Boykin Spaniel dog breed loves a family adventure, especially outdoors. They are eager and easy to train, making them good dogs for novice owners who are active. The Boykin Spaniel gets along with other dogs and pets, doesn’t bark too much, and is well-behaved inside when they get enough exercise."
    },
    {
        "name": "Brussels Griffon",
        "activity": "high",
        "sheds": "little",
        "trainability": "easy",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Spunky with a confidence that is bigger than their bodies, Brussels Griffon dogs lead a life full of zest and gusto. They are bold, playful, funny, and clever dogs that get along well with others. They bark and are known to climb. Families that want a funny and entertaining companion dog in a compact size will fall in love with the Brussels Griffon breed."
    },
    {
        "name": "Bullmastiff",
        "activity": "medium",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The Bullmastiff's personality is a mix of loyalty, protectiveness, and surprising gentleness given their size. These devoted companions are fiercely dedicated to their families, acting as watchful guardians without intense barking. New visitors are typically greeted with suspicion, and only those introduced by a trusted family member might be accepted. Despite their tough appearance, Bullmastiffs are known for their calmness and quiet demeanor. They are not easily fazed, but their bravery is undeniable when threatened."
    },
    {
        "name": "Cairn Terrier",
        "activity": "high",
        "sheds": "little",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "The Cairn Terrier embodies the true spirit of a terrier: plucky, bold, inquisitive, and full of life. Their intelligence is matched by their stubborn streak, ensuring they can be both charming and mischievous. Despite their independence, Cairn Terriers are surprisingly sensitive and responsive to their family's wishes."
    },
    {
        "name": "Cane Corso",
        "activity": "high",
        "sheds": "none",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Gentle and watchful, the Cane Corso dog breed is devoted to its family. They are eager to please and easy to train, which is required for handling such a large dog. The Cane Corso does best with owners who have previous experience with large Mastiff-like dogs. They bark to alert and can be overly cautious if not socialized properly. They get along well with other pets and can make good family dogs with the right training."
    },
    {
        "name": "Cavalier King Charles Spaniel",
        "activity": "high",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Highly valued as companion pets, the Cavalier is sweet, gentle, playful, and eager to please their owners. They are affectionate and quiet, happy to go wherever their owners go, whether to the couch or on a walk. They are affable and easygoing towards other pets, family members, and strangers. They do retain spaniel instincts, so they love to explore, sniff, and chase when playing outside."
    },
    {
        "name": "Chesapeake Bay Retriever",
        "activity": "high",
        "sheds": "none",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The Chesapeake Bay Retriever dog breed is a wonderful dog that could be described as a workaholic. They need to be kept busy and will not enjoy lazing around. They need a purpose and love to be active, such as swimming, running, or hiking. They are independent-minded but much more emotionally complex than the average retriever. This can make them more reserved with strangers. They are protective and polite with their owners.Once Chesapeake Bay Retrievers set their minds on something there is no changing it, making them excellent for search-and-rescue and bomb-detection dogs. Their sensitive souls make them ideal therapy dogs, too."
    },
    {
        "name": "Chihuahua",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Don't be fooled by their dainty size—the Chihuahua packs a spicy personality. These little bundles of curiosity are always on the lookout for adventure, their bright eyes sparkling with mischief and intelligence. While some Chihuahuas possess a regal air, others lean into their feisty side, always ready with a playful nip or a sassy strut. But beneath the bravado lies a heart of pure gold, brimming with love and a devotion that will warm you from the inside out."
    },
    {
        "name": "Cocker Spaniel",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "English Cocker Spaniels are cheerful and active dogs who love nothing more than to be around their human companions. They are eager to please their owners and are deeply devoted and loyal to them, although they can also be sensitive. These social butterflies make great family pets as they get along well with kids and other animals."
    },
    {
        "name": "Collie",
        "activity": "medium",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Every Border Collie is a shepherd at heart, constantly on the lookout for things to round up. No toy is safe from being gathered! These active workers are intelligent and attentive, and they have incredible agility with the ability to change directions on a dime. They can sometimes be considered workaholics since it’s so ingrained in them to be alert at all times."
    },
    {
        "name": "Dachshund",
        "activity": "medium",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Close to the ground, short and sassy Dachshunds aren’t built to win any canine races, but they are built to win hearts. Part cuddle bug and part tiny dictator, this pup can be a pinch stubborn but remains endearing even in its most frustrating moments. Dachshunds make excellent watchdogs since they are always on high alert for their surroundings."
    },
    {
        "name": "Dalmatian",
        "activity": "medium",
        "sheds": "little",
        "trainability": "easy",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The Dalmatian's personality is a whirlwind of energy and devotion. Although known to have a stubborn streak, their loyalty, eagerness to please, and playful nature make them a joy to own, as long as their exercise and stimulation needs are met consistently."
    },
    {
        "name": "Doberman Pinscher",
        "activity": "high",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "If you’re looking for a devoted family dog that will be ever-vigilant in protecting your house, the Doberman Pinscher is a good choice. They’re intelligent guardians, always on alert. Loyal, adventurous, and energetic, they thrive off high exercise needs and mental challenges. They have a gift for obedience and agility and, despite the stereotypes of being aggressive, are sensitive and want to please their owners. Some can be domineering, though, and many are reserved with strangers."
    },
    {
        "name": "English Bulldog",
        "activity": "low",
        "sheds": "little",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The English Bulldog has a face only a mother could love but a personality that everyone adores. They are funny and easygoing dogs that have a mellowness to them. English Bulldogs are eager and willing but can be extremely stubborn when they want to be. Affectionate with their families, they get along well with most other pets and strangers."
    },
    {
        "name": "English Foxhound",
        "activity": "high",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Noble and driven, the English Foxhound gets along well with other dogs, pets, and people. They are generally adaptable –except when they find the scent of something they want to investigate. Then, they’re downright stubborn until they can complete their investigation. They are gentle and friendly, although not necessarily demonstrative in their affection. They bark instead of bay."
    },
    {
        "name": "English Springer Spaniel",
        "activity": "high",
        "sheds": "lot",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "English Springer Spaniels are the straight-A students of the dog world. They’re busy dogs who are intelligent, quick-witted extroverts who aim to please. They are well-mannered and friendly. The English Springer Spaniel breed was developed to be around people so they thrive on human attention and company. As a result, they make excellent family pets who will want to join in on all the family fun. They are active and do well with equally active families. English Springer Spaniels will never be able to turn down an opportunity to play, find items, and carry objects in their mouth, so fetch is truly just the beginning!"
    },
    {
        "name": "English Toy Spaniel",
        "activity": "high",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Happy and smiley, the English Toy Spaniel was bred as a companion dog for the wealthy.  They are eager to please, affectionate, and devoted to their owners. They can have a stubborn streak when training, but consistency and a gentle hand can help motivate them. They are calm, quiet, and friendly dogs that can be aloof with strangers."
    },
    {
        "name": "French Bulldog",
        "activity": "medium",
        "sheds": "low",
        "trainability": "medium",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Clowning around comes naturally to the French Bulldog, who enjoys playing and enchanting their families. They make excellent cuddle buddies and are very happy simply snoozing next to their favorite person. Amiable, sweet, companionable, and willing to please, they make excellent companion dogs."
    },
    {
        "name": "German Shorthaired Pointer",
        "activity": "high",
        "sheds": "lot",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The German Shorthaired Pointer’s dream day is spent swimming, running, and solving puzzles followed by a night curled up next to their owner on the couch. These active dogs are gentle, loving creatures whose brains are sharp and finely tuned to the world around them.  German Shorthaired Pointers have high amounts of energy. They need to have something to do or else they can become unruly. A bored German Shorthaired Pointer can result in poor behavior including digging, chewing, hyperactivity, and getting up to no good.  They are highly specialized working dogs with a history as retrievers and swimmers—they even have webbed feet. Any activity an owner can throw their way they will be happy to tackle—especially if their owners are right there with them."
    },
    {
        "name": "Golden Retriever",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Golden Retrievers have never met a stranger, making friends with everyone they encounter. Sunshine embodied, they are known for their devoted and obedient nature as a family companion. Ignoring a Golden’s active nature and powerful physique can lead to behavior problems, though, so they need to have their physical and mental needs met every day. Some Goldens may be overly exuberant and boisterous, but most are eager to please and enjoy learning. Well-trained and exercised Goldens are calm and mannerly at home, and enthusiastic when invited to play. The Golden Retriever breed’s achievements in competitive obedience are remarkable. This dog especially enjoys games that involve retrieving and loves to carry items in his mouth—it’s preferable that it’s a toy, though, and not a gift from outside."
    },
    {
        "name": "Goldendoodle",
        "activity": "high",
        "sheds": "little",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "moderate",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Overall, Goldendoodles are friendly, energetic, loyal, and loveable. They do well in family life when socialized despite being high-energy dogs. They love to please and are enthusiastic about training. Intelligent and affectionate, they love going on family adventures."
    },
    {
        "name": "Great Dane",
        "activity": "low",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Great Danes are deeply affectionate and incredibly loyal. While their protective nature makes them excellent watchdogs, this instinct can sometimes lead to territorial behavior towards unfamiliar dogs. Early socialization in Great Dane puppies and obedience training are essential for shaping a well-adjusted dog."
    },
    {
        "name": "Great Pyrenees",
        "activity": "medium",
        "sheds": "none",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "You might call the Great Pyrenees a discerning detective. These pups might be apprehensive of new people and friends before getting to know them. Their stubborn personalities make them fiercely independent and occasionally contentious. That streak, however, is just armor for the big soft teddy bear underneath."
    },
    {
        "name": "Harrier",
        "activity": "high",
        "sheds": "little",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Somewhere between the Beagle and English Foxhound in temperament, the Harrier dog is a friendly, pleasant, and sociable hound. They love to track down scents, even if it’s only the trash. They are high-energy dogs that love to be physical. The breed is reserved with strangers, but generally open. They bay loudly when excited, bored, or lonely."
    },
    {
        "name": "Havanese",
        "activity": "low",
        "sheds": "little",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Havanese are busy and curious little pups who love being the center of attention in a family. They play and clown around and are affectionate toward everyone—family, children, strangers, other dogs, pets, you name it. They love to please and pick up training easily. They can bark a lot."
    },
    {
        "name": "Irish Setter",
        "activity": "high",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The Irish Setter approaches everything in life with a good-natured attitude, full of gusto. If given a daily outlet for its energy this breed makes a pleasant companion, but without ample exercise, an Irish Setter can become vocal at home. They are eager to please and be part of family activities."
    },
    {
        "name": "Irish Wolfhound",
        "activity": "low",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Looking for a gentle giant whose heart is as big as their body? You’ve found them in the Irish Wolfhound. Their friendly, graceful disposition allows them to get along with just about anyone. They love to be around their humans and will crave quality time with their loved ones. They enjoy being around other dogs (though, it should be known that some other breeds may be intimidated by their size). As puppies, Wolfhounds can be overly energetic, and boisterous, and require a lot of metaphorical hand-holding. However, it’s absolutely worth it when they reward you with their devoted love and companionship in return."
    },
    {
        "name": "Italian Greyhound",
        "activity": "high",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "A sighthound in a small package, the Italian Greyhound shares the characteristics of the larger versions. This little dog loves to run and chase but has a super sensitive disposition. They are clean, gentle, and shy, and love to snuggle because they are affectionate and trying to keep warm. They can be shy around strangers to the point of disinterest but are devoted to their families and get along well with kids, other dogs, and pets in their familial unit. Since they're so small, they can easily get hurt by rough play with kids or bigger dogs."
    },
    {
        "name": "Japanese Chin",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Devoted, quiet, calm, and eager, the Japanese Chin is a true companion dog that loves doing whatever its owner is doing, whether out walking or curled up on the couch. They are friends to everyone, gently playful, and loving. They have an almost cat-like demeanor and have some cat-like behaviors, such as climbing, jumping, and washing their faces with their front paws."
    },
    {
        "name": "Keeshond",
        "activity": "medium",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The cheerful Keeshond didn’t get the nickname the “Smiling Dutchman” for no reason. Their happy-go-lucky demeanor is one of their many charms. Beneath that charming, fluffy exterior, though, lies a sharp-minded watchdog with a penchant for vocal expression."
    },
    {
        "name": "Komondor",
        "activity": "low",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "Bred to be independent watchdogs, the Komondor can be stubborn. Socialization is essential to have them live as family companions, although they do best as working livestock dogs, even today. They are reserved with strangers and weary of other dogs, but good with family pets and livestock. They are happiest when they have a job to do that requires protecting. They can be calm, but courageous when needed."
    },
    {
        "name": "Kuvasz",
        "activity": "high",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Despite a gentle look, the Kuvasz is a sentinel dog who prefers to work rather than be a companion. They were originally bred to guard livestock and to live among the animals they protected. They can be gentle but do best in families with older children who can respect the dog’s boundaries. Reserved with strangers, the Kuvasz is calm and good-natured with other pets and livestock. They are devoted and loyal but prefer to show that through their work rather than cuddles."
    },
    {
        "name": "Labrador Retriever",
        "activity": "high",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Labradors are the epitome of boundless enthusiasm and unwavering loyalty. These affectionate goofballs crave human companionship. With a seemingly endless appetite for life (and food, too), Labs are always up for an adventure. Their gentle nature and patience make them ideal family companions, thriving in homes with children and other pets alike.  Eager to please, they're quick learners and excel at various activities, from obedience to agility. However, their insatiable curiosity and love for treats may require a firm but loving hand to resist their charming antics. As for their tails? They constantly signal the dog’s joy."
    },
    {
        "name": "Leonberger",
        "activity": "high",
        "sheds": "none",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "Leonberger dogs are easy-going and loyal. They are known for their placid and even temperament, but their confidence and strength hint at their watchdog ancestry. Leonbergers are surprisingly playful for their size and endlessly patient with children. They’re also generally quiet and calm indoors, making them wonderful housemates, but their watchful nature ensures they'll always be alert and ready to protect their loved ones."
    },
    {
        "name": "Lhasa Apso",
        "activity": "low",
        "sheds": "little",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "While this lion dog might look like a happy-go-lucky lap pup, the Lhasa Apso is a tough, independent, and bold breed. They have been bred for thousands of years as companions to Tibetan monks and can adapt well to small spaces despite also loving romping around outside and mental games. They love nothing more than being close to their owners, and going on as many adventures as they’ll allow. They can be reserved with strangers but are overall highly adaptable."
    },
    {
        "name": "Manchester Terrier",
        "activity": "high",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "medium",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Clean, tidy, and compact, the Manchester Terrier is a well-mannered dog. They are sensitive but devoted members of the family and love nothing more than napping after a good romp outdoors. They are game for adventures, especially if they involve digging. They are busy and curious dogs."
    },
    {
        "name": "Mastiff",
        "activity": "high",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Good-natured, calm, easygoing, and surprisingly gentle, the Mastiff gets a bad rap thanks to its size. They are well-mannered dogs inside but need sufficient room to stretch their massive bodies. They’re loyal and while not exactly affectionate, show their devotion to their families. They can be good with older children."
    },
    {
        "name": "Miniature Schnauzer",
        "activity": "low",
        "sheds": "little",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Mini Schnauzers are playful, inquisitive, alert, and spunky—just like your most confident and charming friend! They are well-mannered and love being part of family life. Compared to their larger Schnauzer cousins, they are less bossy and more friendly than other terrier breeds. These little geniuses can be stubborn, but they are usually obedient. Mini Schnauzers adore the company of children, even if some of them might be a bit chatty. They’re the life of the party, always ready to entertain and be entertained!"
    },
    {
        "name": "Norwegian Elkhound",
        "activity": "medium",
        "sheds": "little",
        "trainability": "easy",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Norwegian Elkhound dogs are introverted extroverts. Initially reserved, they soon open up and show off their confident, bold, and playful personality. These dogs are social, vocal, and friendly, always by their owners’ sides. They get along well with other dogs when properly socialized.  The Norwegian Elkhound breed is a natural athlete, brimming with agility and endurance. They are happiest when they are having adventures outdoors, preferably in cold climates. The Norwegian Elkhound is a blend of strength, sensitivity, loyalty, and independence."
    },
    {
        "name": "Norwich Terrier",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Lively with a bravado that is disproportionate to their bodies, the Norwich Terrier dog breed is ready to tackle any adventure, preferably with their owners by their side. They are perky and loving companion dogs who have active minds and bodies. They love to be entertained. Often more stubborn than other terrier breeds, the Norwich Terrier dog has an independent and quick mind that the right owner will find endearing."
    },
    {
        "name": "Nova Scotia Duck Tolling Retriever",
        "activity": "medium",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Duck Tollers possess boundless energy and a playful spirit that makes them a joy to have around. Whether you're training for agility competitions or simply enjoying a walk, Nova Scotia Duck Tolling Retrievers give their all with infectious enthusiasm. These intelligent pups may surprise you with their \"Toller scream\" when particularly excited, but their friendly nature and trainability make them wonderful companions for active families and dog enthusiasts."
    },
    {
        "name": "Old English Sheepdog",
        "activity": "high",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Old English Sheepdogs are jolly giants who are intelligent, loving, and super-friendly. They thrive on human companionship and are well-mannered dogs that make excellent family pets.  Once used to drive cattle (not herd sheep as you might think!), they are good watchdogs with a protective yet gentle nature. They look out for their families, especially children, who they treat as part of their herd. There is a lot of energy in such a large dog, so they need plenty of mental and physical stimulation to get the wiggles out. If not, they can become stubborn and noisy."
    },
    {
        "name": "Papillon",
        "activity": "high",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Papillons are energetic, alert, and friendly little dogs that love to cuddle and be involved in family activities. These cheerful and intelligent pups get along well with other pets and children, though their small size means gentle play is important. While typically social butterflies (pun intended), some Papillons can be timid around strangers."
    },
    {
        "name": "Pekingese",
        "activity": "high",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "While they are small pups, they are not timid lap dogs. Courageous and tenacious, these Chinese lion dogs can be outgoing and loving although not overly affectionate. Pekingese dogs are fiercely independent and have a stubborn streak, and some can be aloof. They can be playful around family members but might not be playful enough for children. They don’t like being roughly handled and can be injured easily by small children."
    },
    {
        "name": "Pembroke Welsh Corgi",
        "activity": "low",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Tiny but mighty, the Pembroke Welsh Corgi is a large dog in a small package, with the bark to prove it. These strong, athletic, lively little dogs are the best of both worlds: a fearless, independent, hardworking athlete who’s well-mannered and does well in family life. Pembroke Welsh Corgis are bright, intelligent, and sensitive. They equally love curling up on the couch and being active, especially when their owners are involved. These dogs are hopelessly devoted to their family and make excellent watchdogs. They are friendly and generally get along well with everyone."
    },
    {
        "name": "Pomeranian",
        "activity": "medium",
        "sheds": "none",
        "trainability": "easy",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "These pint-sized powerhouses are bursting with pep. Don't let their poofy exteriors fool you, Pomeranians are vigilant watchdogs, too. Playtime with other dogs is important for socialization and to ensure good behavior. These tiny alarm systems are ready to shout out should anything be suspicious. Even with all that bark, they're delicate little creatures under all that fur."
    },
    {
        "name": "Poodle",
        "activity": "low",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Standard Poodles are a high-spirited, energetic breed who love to exercise, solve puzzles, and play with their owners. They enjoy being around their human companions and require a significant amount of care and attention. They are quick-witted, highly intelligent, and love to have fun, but do tend to get bored easily. You can commonly find them running around, swimming,  playing fetch, and loving on their owners."
    },
    {
        "name": "Rhodesian Ridgeback",
        "activity": "high",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Assertive without being aggressive, the Rhodesian Ridgeback is protective of their family units. They do well with older children but could be too bouncy for smaller ones. Strong-willed, independent, powerful, and large, they can come off as domineering. Two adult male Rhodesian Ridgebacks should not be left alone together. They are weary of strangers, although they do well with other dogs and sometimes cats if properly socialized with them."
    },
    {
        "name": "Rottweiler",
        "activity": "medium",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Elegant, graceful, and more loveable than they are often depicted, Rottweilers are large, self-assured dogs. They can be headstrong and stubborn, and when not trained properly, can become aggressive or guarded towards strangers. They can also be overly assertive if they believe their family or property is being threatened. They need socialization, a high level of training, and vigorous daily exercise to become more of a gentle giant than an intimidating household pet."
    },
    {
        "name": "Saluki",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Think of Salukis as the cat-like creatures of the dog world: independent yet fiercely loyal. While they form deep bonds with their humans, don't expect a slobbery welcome home; their greetings are more of a regal nod. Gentle and dignified, Salukis are known to provide their humans with quiet affection."
    },
    {
        "name": "Samoyed",
        "activity": "low",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Gentle and playful with a heart of gold, a Samoyed has been bred for companionship from its origins. They bond closely with their families and are amiable with strangers, other pets, and other dogs. They are relatively chill indoors so long as they are exercised physically and mentally. They can have an impish streak if these needs are not met, and they’ll bark and dig excessively. Owners will need nerves of steel to combat a Samoyed’s stubborn streak, but they are generally responsive and eager to please their family, although they might herd small children."
    },
    {
        "name": "Scottish Terrier",
        "activity": "high",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "Rugged and tough, the Scottish Terrier dog is a smart and determined dog. They are always ready for action and can often be fearless and feisty. Socialization is crucial to ensure they become well-mannered dogs. Reserved but amiable with strangers once they get to know them, they are utterly devoted family members. They tend to dig and bark, which can be overcome with proper training."
    },
    {
        "name": "Shiba Inu",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Shiba Inus form strong bonds with their humans without being overly clingy. When the headstrong Shiba Inu doesn't get what they want, they might scream like a banshee. The high-pitched sound is their signature chord. A confident and lively dog, they love to be outdoors where they can run free and wild. They are calm indoors, although they can be alert and reserved with strangers."
    },
    {
        "name": "Shih Tzu",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Spunky, sweet, loyal, and vivacious, a Shih Tzu bonds closely with its owner. They are known for having a pep in their step and a personality that makes them seem like perpetual puppies. Affectionate, good with family life, and low on exercise needs, these little sweethearts make excellent companions. They can have a stubborn or tough streak."
    },
    {
        "name": "Siberian Husky",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Siberian Huskies retain their working spirit even in the most docile environment; they are always ready to be active companions. They are friendly, gentle, and watchful with an independent streak. Though generally quiet, they can occasionally express themselves with joyful howls."
    },
    {
        "name": "Standard Schnauzer",
        "activity": "low",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Fun-loving and smart, the Standard Schnauzer dog is a bold one. They are whip-smart but can also be stubborn. If their needs aren’t met, they can be mischievous, making their own fun. Patience, structure, and a gentle hand with lots of positive reinforcement are what a Standard Schnauzer needs to be successful at training. Devoted to their families, they do best with older children as they have high stimulation needs."
    },
    {
        "name": "Tibetan Spaniel",
        "activity": "low",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Bold and often stubborn, the Tibetan Spaniel dog is an independent thinker with a sensitive side. They are generally very happy and enjoy being with their families, whether on outings or just curled up on the couch. They get along well with other dogs but can be aloof with strangers."
    },
    {
        "name": "Tibetan Terrier",
        "activity": "low",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "While called a terrier, the Tibetan Terrier is not a terrier and is only named as such based on their size. They don’t have any terrier qualities, but instead are charming and loyal companion dogs driven by owner interaction, not work. Eager to please yet sensitive, they are generally good-natured and affectionate. They make good family companions for families willing to take them on adventures. Owners might often find them on the back of a couch or on a counter."
    },
    {
        "name": "Toy Fox Terrier",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Dynamic and bold, the Toy Fox Terrier—also known as the TFT dog—is full of fun and feistiness. They are tiny investigators, ready to seek out adventures indoors or outside. Play is a priority for them, whether with their owners or with toys. Toy Fox Terrier dogs love to entertain and be entertained, but their favorite place is always going to be by their owner’s side. Suspicious of strangers, they can overcome this with socialization."
    },
    {
        "name": "Vizsla",
        "activity": "high",
        "sheds": "none",
        "trainability": "easy",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "With its larger-than-life personality, the Vizsla is an affectionate and energetic companion. These sensitive souls crave activity and thrive on positive training sessions. Their strong bond with their family makes them natural protectors, but it also means they aren’t a fan of being left alone. Vizslas are brimming with energy, making them perfect for those who love getting active outdoors. While some Vizslas might exhibit stubbornness, shyness, or excitability, their overall temperament is gentle, affectionate, and eager to please."
    },
    {
        "name": "Weimaraner",
        "activity": "medium",
        "sheds": "none",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "​​Weimaraners are balls of large energy with friendly and bold personalities. They crave exercise and love to run, hike, or join you in any outdoor activity. They can become frustrated and destructive without an outlet for their boundless spirit. While friendly and eager to please, these silver dogs can also be stubborn and require consistent training.Ideally suited for active families without small children, Weimaraners thrive on camaraderie with their trusted humans and are known for being loyal, fun-loving companions. Their intelligence and alertness also make them excellent watchdogs. However, their strong personalities and need for training might not be ideal for first-time dog owners."
    },
    {
        "name": "Whippet",
        "activity": "low",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Quiet and devoted, Whippets are the most outgoing and amenable of the sighthounds and have a reputation for being gentle with children. They are calm and quiet indoors but love a good romp outside to get the zoomies out. They can be sensitive mentally and physically and need to be handled gently and with love."
    },
    {
        "name": "Wirehaired Pointing Griffon",
        "activity": "low",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Skilled at retrieving and pointing, the Wirehaired Pointing Griffon dog is independent yet friendly. They do well in family life and are devoted and trustworthy dogs with a good sense of humor. Their trusting nature extends beyond family—they’ve never met a stranger, whether human or animal."
    },
    {
        "name": "Yorkshire Terrier",
        "activity": "medium",
        "sheds": "little",
        "trainability": "moderate",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Yorkies pack a lot of attitude into their small bodies. Lively, curious, and into everything, owners will have to get used to being tailed everywhere by this inquisitive shadow. These pups need a lot of stimulation. Long walks are helpful, but games and toys keep their busy brains occupied."
    },
    {
        "name": "Anatolian Shepherd",
        "activity": "high",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The Anatolian Shepherd is a paradox of loyalty and independence. Deeply devoted to their family, they take their guardian role seriously. While calm and easygoing at home, they are serious, naturally wary of strangers, and highly territorial. This protectiveness can manifest as barking when unfamiliar sights or sounds trigger their alert nature. Their focus on guarding duties might not match a child's desire for an overly playful companion, making them better suited for an adult-only home with a more experienced owner."
    },
    {
        "name": "Australian Cattle Dog / Blue Heeler",
        "activity": "high",
        "sheds": "lot",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Often cited as headstrong, stubborn, energetic, and hardworking, Australian Cattle Dogs love a challenge, whether physical or mental. Natural Energizer Bunnies, these dogs love to silently herd and learn new things. Given their instincts, they tend to nip at heels, especially when small children are running but do well with older children."
    },
    {
        "name": "Bearded Collie",
        "activity": "medium",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Bearded Collies are enthusiastic about everything and everyone they encounter. They are affectionate, gentle, and charismatic dogs who are eager to please and eager to learn. Active owners are best for them as they have a high level of endurance and want to be physically active, no matter the weather. Bearded Collie dogs are intelligent and can get easily bored with unchallenging routines so the busier they can be, the better. “Beardies” as the Bearded Collie breed is sometimes called, love people and love to be included in anything their owners are doing. They are sensitive dogs who wear their hearts on their sleeves."
    },
    {
        "name": "Bergamasco Sheepdog",
        "activity": "low",
        "sheds": "lot",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The Bergamasco is a working dog, naturally inclined to guard and herd. To make it in family life, they need early socialization and ongoing training. Though there is a strong desire to please, this is not an ideal dog for a first-time dog owner."
    },
    {
        "name": "Bernese Mountain Dog",
        "activity": "medium",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Bernese Mountain Dogs were originally bred to work. They have a playful enthusiasm for tasks and love to be given a job, whether pulling a cart, carrying a backpack, or simply fetching the newspaper. They are easygoing and calm family companions who are sensitive, loyal, devoted, and gentle with children."
    },
    {
        "name": "Borzoi",
        "activity": "medium",
        "sheds": "none",
        "trainability": "easy",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Quiet, elegant, and gentle, these dogs are well-mannered indoors. Once outside, though, their instincts kick in and they can race with wild abandon, chasing anything small that runs. Borzoi can be independent, sensitive, and somewhat difficult to train, especially regarding recall. Strangers are not their forte. They are generally good with children but might be too boisterous for the extremely young and not playful enough."
    },
    {
        "name": "Boston Terrier",
        "activity": "high",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Nicknamed “The American Gentleman” for their impeccable manners, Bostons are lively, happy dogs that love to be around humans. They enjoy shadowing their owners and will always want to get in on the fun happening around them. Outgoing, social, and very affectionate, these pups are always eager to be loved on and for some mid-day cuddles.  This breed is clever, determined, and very adaptable to training. They live to chase balls and can often get so excited by playing fetch with their humans that they get the “zoomies.” They take their play time very seriously and can get a little boisterous and strong-willed—sometimes needing to take breaks to help them not get overstimulated. Even though they have Terrier in their name, Bostons do not fit a typical Terrier personality and avoid a lot of mischief the breed classification is commonly associated with."
    },
    {
        "name": "Boxer",
        "activity": "high",
        "sheds": "none",
        "trainability": "difficult",
        "barks": "medium",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Boxers have boundless energy and keep a puppy-like zest for life well into adulthood. Their exuberant spirit is best handled by owners who can match their activity levels. Boxers thrive on human interaction and can become restless and destructive when left alone. They’re a family’s heart and soul, but they do require a home that can keep up with their playful antics. While they adore children, their playful personality might be overwhelming for toddlers."
    },
    {
        "name": "Brittany Spaniel",
        "activity": "low",
        "sheds": "little",
        "trainability": "easy",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Exceptionally bright and curious, the Brittany Spaniel has heaps of energy. They love to run, sniff, play, and romp and might exhaust their owners. They hate being alone and become destructive if left too long by themselves. They can be sensitive. If they receive good mental and physical stimulation, they are an ideal combination of a hard-working dog and a loyal companion."
    },
    {
        "name": "Chinese Crested Dog",
        "activity": "medium",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "A playful companion dog that’s as sensitive emotionally as it is physically, the Chinese Crested is a devoted dog. They are good with other dogs, people, pets, and most children, albeit younger and more unpredictable ones can be stressful to these delicate dogs."
    },
    {
        "name": "German Shepherd Dog",
        "activity": "low",
        "sheds": "little",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Often described as a “one man (or woman) dog,” German Shepherds form extremely strong, affectionate, and loyal bonds with their handlers, wanting to be with them as much as possible. A well-behaved, well-trained German Shepherd should be bold, confident, swift, and intelligent, as well as calm and steady. They should listen well to their owner and be eager to learn and easy to train. They are sensitive and slow to mature, which might require more patience and effort than one might think. But the trade-off is a smiley, happy, Einstein of a dog who will stick by your side no matter what."
    },
    {
        "name": "Giant Schnauzer",
        "activity": "high",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Rambunctious and playful, Giant Schnauzers are guard dogs by nature. They can be loud and chatty, which might not fit with a family with small children. Otherwise, they are devoted and loyal to their families and reserved with strangers, potentially even being assertive with other dogs. Intelligent, bouncy, and seemingly with never-ending energy, they make ideal companions for owners who can give them jobs to do, take them on outdoor adventures, and let them be leaders when they want to."
    },
    {
        "name": "Labradoodle",
        "activity": "high",
        "sheds": "little",
        "trainability": "easy",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "moderate",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Labradoodle dogs have the personality of a fun, active, energetic child-at-heart. They are extremely affectionate and will want to curl up and snuggle in your lap—even the massive-sized ones. Labradoodles are giant balls of energy: always ready to play, swim, run, and wait for you to catch up. This Labrador Retriever and Poodle mixed breed thrives on human companionship and wants nothing more than to be around and please their owners. Labradoodles are social, chatty, talkative, and want to feel like a member of the family. They are ideal pets to have around children due to their easy, loveable nature. They are highly intelligent dogs and food-motivated, which comes in handy when training. They make great watchdogs and will alert you when you have visitors; however, Labradoodles are all bark. Their alert will immediately be followed by the uncontrollable desire to play with the visitors."
    },
    {
        "name": "Miniature Pinscher",
        "activity": "high",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "Though classified as a Toy dog, the Miniature Pinscher packs a tenacious terrier's spirit in a pint-sized package. Pinscher translates to \"terrier,\" a fitting description for their bold, fearless, and inquisitive personalities. Min Pins are known to be one of the most active terrier breeds, so be prepared for an energetic partner in crime. Their playful and curious nature can be endearing, but their stubborn streak and independence require consistent training and loads of patience. While reserved with strangers, they shower their loved ones with affection."
    },
    {
        "name": "Newfoundland Dog",
        "activity": "medium",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "The Newfoundland's most defining characteristic—besides their large physical size— is their gentle and affectionate temperament. These calm, easygoing, and patient pups are known for their friendly demeanor, making them wonderful companions for everyone they meet. Their loyalty extends to their family, where they act as caring protectors."
    },
    {
        "name": "Plott Hound",
        "activity": "medium",
        "sheds": "little",
        "trainability": "difficult",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The Plott Hound has all the characteristics of a scent hound—determined, unrelenting, and deaf to your commands when they find something they want to follow. They are loyal and eager to please dogs that warm up quickly to strangers. They aren’t as friendly with other dogs as some hound breeds and can become protective easily, defaulting to their instincts."
    },
    {
        "name": "Saint Bernard",
        "activity": "high",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": false,
        "kidFriendly": true,
        "personality": "Saint Bernards have an impressively calm demeanor for a dog of such stature. They are affectionate, easygoing, and good-humored dogs who are happiest when with their human companions. It would be hard-pressed to find a dog more devoted to their family.Saint Bernards are a relatively quiet breed, but when they bark you will hear it—especially if they are defending owners or property. They are a trustworthy and very loyal breed that will love to follow their owners around, snuggle, and jump up on your lap, unaware or uncaring of their size."
    },
    {
        "name": "Shar-Pei",
        "activity": "high",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "low",
        "affectionate": false,
        "talkative": "",
        "grooming": "medium",
        "hypoallergenic": false,
        "kidFriendly": false,
        "personality": "The Chinese Shar-Pei’s personality is a complex blend of loyalty and independence. Well-socialized pups are devoted to their families and playful at times but often possess an aloof demeanor. Their stubborn streak can emerge without proper training, manifesting as territorial behavior. Shar-Pei are naturally wary of strangers, requiring careful introductions. Other pets can be a coin toss; they may integrate well with cats raised alongside them, but other dogs might be met with suspicion or even aggression."
    },
    {
        "name": "Shetland Sheepdog / Sheltie",
        "activity": "medium",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": false,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "Bright, sensitive, and willing to please, the Sheltie is an adaptable and hearty farm dog. They are devoted to their families. Their active minds take some time to quiet, and learning how to settle is an important part of their training. They get along well with children, albeit older ones since they are prone to nipping heels and herding while playing which might not be suitable for smaller children. Strangers might find them aloof and reserved, or on the end of a barking fit—Shelties take their job as watchdogs very seriously."
    },
    {
        "name": "West Highland White Terrier / Westie",
        "activity": "medium",
        "sheds": "lot",
        "trainability": "easy",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "high",
        "hypoallergenic": true,
        "kidFriendly": true,
        "personality": "Westies are courageous and cheeky pups are undeniably charming. They shower their families and friends with affection and loyalty. While trainable with patience and encouragement, their independent terrier spirit shines through. Always alert, Westies make excellent watchdogs, their barks leaving no doubt when they sense something amiss. Despite their stubborn streak, their playful and happy nature makes them a joy to have around. Just be prepared for A West Highland White Terrier’s boundless curiosity, energetic playtime demands, and the occasional vocal outburst."
    },
    {
        "name": "Wheaten Terrier",
        "activity": "low",
        "sheds": "none",
        "trainability": "moderate",
        "barks": "high",
        "affectionate": true,
        "talkative": "",
        "grooming": "low",
        "hypoallergenic": true,
        "kidFriendly": false,
        "personality": "The Wheaten Terrier can be playful and affectionate with their owners, although you should expect a headstrong streak or a lack of motivation akin to a teenager when it comes to doing things they don’t want to do, such as training. They dig and jump and bark to alert, although less than other similar terrier breeds."
    }
];