export const cats = [
  {
    name: "Persian",
    minWeight: "9",
    maxWeight: "20",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Persian",
  },
  {
    name: "Maine Coon",
    minWeight: "6",
    maxWeight: "11",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Maine_Coon_cat_by_Tomitheos.JPG/250px-Maine_Coon_cat_by_Tomitheos.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Maine_Coon",
  },
  {
    name: "Ragdoll",
    minWeight: "9",
    maxWeight: "17",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Ragdoll_from_Gatil_Ragbelas.jpg/250px-Ragdoll_from_Gatil_Ragbelas.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Ragdoll",
  },
  {
    name: "Siamese",
    minWeight: "5",
    maxWeight: "18",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Siamese",
  },
  {
    name: "British Shorthair",
    minWeight: "9",
    maxWeight: "13",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Britishblue.jpg/250px-Britishblue.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/British_Shorthair",
  },
  {
    name: "Abyssinian",
    minWeight: "9",
    maxWeight: "11",
    activity: "low",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Abyssinian",
  },
  {
    name: "Birman",
    minWeight: "10",
    maxWeight: "15",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Birmanstrofe.jpg/250px-Birmanstrofe.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Birman",
  },
  {
    name: "Oriental",
    minWeight: "5",
    maxWeight: "15",
    activity: "medium",
    price: "$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Oriental",
  },
  {
    name: "Scottish Fold",
    minWeight: "6",
    maxWeight: "16",
    activity: "low",
    price: "$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_Scottihs_Fold_Cat.png/250px-Black_Scottihs_Fold_Cat.png",
    usefulLink: "https://en.wikipedia.org/wiki/Scottish_Fold",
  },
  {
    name: "Sphynx",
    minWeight: "9",
    maxWeight: "12",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Sphynx_-_cat._img_031.jpg/250px-Sphynx_-_cat._img_031.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Sphynx",
  },
  {
    name: "Devon Rex",
    minWeight: "10",
    maxWeight: "16",
    activity: "low",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Devon_Rex_Cassini.jpeg/250px-Devon_Rex_Cassini.jpeg",
    usefulLink: "https://en.wikipedia.org/wiki/Devon_Rex",
  },
  {
    name: "American Shorthair",
    minWeight: "5",
    maxWeight: "13",
    activity: "low",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Jewelkatz_Romeo_Of_Stalker-Bars.jpg/250px-Jewelkatz_Romeo_Of_Stalker-Bars.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/American_Shorthair",
  },
  {
    name: "Norwegian Forest",
    minWeight: "10",
    maxWeight: "15",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Norwegian_Forest_Cat_in_snow.jpg/250px-Norwegian_Forest_Cat_in_snow.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Norwegian_Forest",
  },
  {
    name: "Exotic Shorthair",
    minWeight: "9",
    maxWeight: "15",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Ginger_Exotic_Shorthair.jpg/250px-Ginger_Exotic_Shorthair.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Exotic_Shorthair",
  },
  {
    name: "Russian Blue",
    minWeight: "6",
    maxWeight: "17",
    activity: "high",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Russian_blue.jpg/250px-Russian_blue.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Russian_Blue",
  },
  {
    name: "Burmese",
    minWeight: "9",
    maxWeight: "13",
    activity: "high",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Burmese",
  },
  {
    name: "Siberian",
    minWeight: "7",
    maxWeight: "16",
    activity: "low",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Siberia_%28orthographic_projection%29.svg/250px-Siberia_%28orthographic_projection%29.svg.png",
    usefulLink: "https://en.wikipedia.org/wiki/Siberian",
  },
  {
    name: "Tonkinese",
    minWeight: "5",
    maxWeight: "12",
    activity: "low",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Tonkinese",
  },
  {
    name: "Chartreux",
    minWeight: "7",
    maxWeight: "18",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/IC_Blue_Melody_Flipper_CHA_male_EX1_CACIB.jpg/250px-IC_Blue_Melody_Flipper_CHA_male_EX1_CACIB.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Chartreux",
  },
  {
    name: "Turkish Angora",
    minWeight: "9",
    maxWeight: "16",
    activity: "high",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Turkish_Angora_in_Ankara_Zoo_%28AO%C3%87%29.JPG/250px-Turkish_Angora_in_Ankara_Zoo_%28AO%C3%87%29.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Turkish_Angora",
  },
  {
    name: "Himalayan",
    minWeight: "5",
    maxWeight: "16",
    activity: "low",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Himalayan",
  },
  {
    name: "Manx",
    minWeight: "6",
    maxWeight: "14",
    activity: "low",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Manx",
  },
  {
    name: "Cornish Rex",
    minWeight: "5",
    maxWeight: "15",
    activity: "low",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Rex_staredown.jpg/250px-Rex_staredown.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Cornish_Rex",
  },
  {
    name: "Ragamuffin",
    minWeight: "7",
    maxWeight: "20",
    activity: "low",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Ragamuffin",
  },
  {
    name: "Balinese",
    minWeight: "7",
    maxWeight: "20",
    activity: "high",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Balinese",
  },
  {
    name: "Selkirk Rex",
    minWeight: "7",
    maxWeight: "12",
    activity: "low",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/PolloSelkirkRex.jpg/250px-PolloSelkirkRex.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Selkirk_Rex",
  },
  {
    name: "Oriental Longhair",
    minWeight: "7",
    maxWeight: "14",
    activity: "medium",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/JPG_12.jpg/250px-JPG_12.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Oriental_Longhair",
  },
  {
    name: "Japanese Bobtail",
    minWeight: "5",
    maxWeight: "11",
    activity: "medium",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/JapaneseBobtailBlueEyedMi-ke.JPG/250px-JapaneseBobtailBlueEyedMi-ke.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Japanese_Bobtail",
  },
  {
    name: "Singapura",
    minWeight: "8",
    maxWeight: "14",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/250px-Flag_of_Singapore.svg.png",
    usefulLink: "https://en.wikipedia.org/wiki/Singapura",
  },
  {
    name: "American Wirehair",
    minWeight: "8",
    maxWeight: "19",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/American_Wirehair_-_CFF_cat_show_Heinola_2008-05-04_IMG_8721.JPG/250px-American_Wirehair_-_CFF_cat_show_Heinola_2008-05-04_IMG_8721.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/American_Wirehair",
  },
  {
    name: "American Curl",
    minWeight: "8",
    maxWeight: "16",
    activity: "low",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/American_curl_2.jpg/250px-American_curl_2.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/American_Curl",
  },
  {
    name: "Somali",
    minWeight: "8",
    maxWeight: "18",
    activity: "low",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Somali",
  },
  {
    name: "Snowshoe",
    minWeight: "10",
    maxWeight: "17",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Snowshoe",
  },
  {
    name: "Bengal",
    minWeight: "7",
    maxWeight: "20",
    activity: "low",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bengal_in_Asia.jpg/250px-Bengal_in_Asia.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bengal",
  },
  {
    name: "Ocicat",
    minWeight: "8",
    maxWeight: "16",
    activity: "high",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Topspot_La_Colombina_%28Liina%29_OCI_c_24_female_kitten_EX1.JPG/250px-Topspot_La_Colombina_%28Liina%29_OCI_c_24_female_kitten_EX1.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Ocicat",
  },
  {
    name: "Egyptian Mau",
    minWeight: "10",
    maxWeight: "16",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/RoyalNefertt_Serket_of_AchetAton.jpg/250px-RoyalNefertt_Serket_of_AchetAton.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Egyptian_Mau",
  },
  {
    name: "Turkish Van",
    minWeight: "5",
    maxWeight: "11",
    activity: "low",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Red_Turkish_Van_Male_Tom.png/250px-Red_Turkish_Van_Male_Tom.png",
    usefulLink: "https://en.wikipedia.org/wiki/Turkish_Van",
  },
  {
    name: "Pixiebob",
    minWeight: "8",
    maxWeight: "12",
    activity: "medium",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Uptoyou_duFarWestwithBePacific2.jpg/250px-Uptoyou_duFarWestwithBePacific2.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Pixiebob",
  },
  {
    name: "LaPerm",
    minWeight: "9",
    maxWeight: "15",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Laperm_LH_blacktortie_white.jpg/250px-Laperm_LH_blacktortie_white.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/LaPerm",
  },
  {
    name: "Peterbald",
    minWeight: "10",
    maxWeight: "17",
    activity: "medium",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b7/Tamila_the_lilac_tabby_Peterbald_cat.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Peterbald",
  },
  {
    name: "Korat",
    minWeight: "10",
    maxWeight: "15",
    activity: "high",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Face_et_profil_du_korat.JPG/250px-Face_et_profil_du_korat.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Korat",
  },
  {
    name: "Colorpoint Shorthair",
    minWeight: "7",
    maxWeight: "19",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Chocolate_Tortie_Pt_11636-140.jpg/250px-Chocolate_Tortie_Pt_11636-140.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Colorpoint_Shorthair",
  },
  {
    name: "Savannah",
    minWeight: "9",
    maxWeight: "17",
    activity: "high",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Savannah",
  },
  {
    name: "Chantilly-Tiffany",
    minWeight: "6",
    maxWeight: "14",
    activity: "low",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Chantilly-cat-fancy-1995_%28cropped%29.jpg/250px-Chantilly-cat-fancy-1995_%28cropped%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Chantilly-Tiffany",
  },
  {
    name: "Bombay",
    minWeight: "8",
    maxWeight: "17",
    activity: "medium",
    price: "$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/BackBay_skyline.jpg/330px-BackBay_skyline.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bombay",
  },
  {
    name: "Munchkin",
    minWeight: "10",
    maxWeight: "14",
    activity: "high",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Munchkins.png/250px-Munchkins.png",
    usefulLink: "https://en.wikipedia.org/wiki/Munchkin",
  },
  {
    name: "Lykoi",
    minWeight: "6",
    maxWeight: "18",
    activity: "low",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/8-month-old_male_Lykoi.jpg/250px-8-month-old_male_Lykoi.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Lykoi",
  },
  {
    name: "Tonkinese",
    minWeight: "7",
    maxWeight: "15",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Tonkinese",
  },
  {
    name: "Cymric",
    minWeight: "10",
    maxWeight: "16",
    activity: "medium",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Cymric",
  },
  {
    name: "European Burmese",
    minWeight: "6",
    maxWeight: "11",
    activity: "medium",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/British_burmese_-_Andel_Alois_at_Cat_show.JPG/250px-British_burmese_-_Andel_Alois_at_Cat_show.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/European_Burmese",
  },
  {
    name: "Foldex",
    minWeight: "10",
    maxWeight: "18",
    activity: "high",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Cachorro_de_Gato_FoldEx_%28%22Belisario_del_Laberinto%22%29.JPG/250px-Cachorro_de_Gato_FoldEx_%28%22Belisario_del_Laberinto%22%29.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Foldex",
  },
  {
    name: "Highlander",
    minWeight: "7",
    maxWeight: "18",
    activity: "low",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Highlander",
  },
  {
    name: "Javanese",
    minWeight: "10",
    maxWeight: "12",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Javanese",
  },
  {
    name: "Khao Manee",
    minWeight: "7",
    maxWeight: "13",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Khaomanee_cat.jpg/250px-Khaomanee_cat.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Khao_Manee",
  },
  {
    name: "Kurilian Bobtail",
    minWeight: "6",
    maxWeight: "17",
    activity: "high",
    price: "$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Kurilian_bobtail.JPG/250px-Kurilian_bobtail.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Kurilian_Bobtail",
  },
  {
    name: "Minuet",
    minWeight: "8",
    maxWeight: "12",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Minuet",
  },
  {
    name: "Nebelung",
    minWeight: "6",
    maxWeight: "19",
    activity: "high",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Nebelung_female_cat.jpg/250px-Nebelung_female_cat.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Nebelung",
  },
  {
    name: "Serengeti",
    minWeight: "6",
    maxWeight: "17",
    activity: "high",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Serengeti",
  },
  {
    name: "Skookum",
    minWeight: "7",
    maxWeight: "17",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Skookum",
  },
  {
    name: "Sokoke",
    minWeight: "8",
    maxWeight: "13",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Sokoke_dalili.jpg/250px-Sokoke_dalili.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Sokoke",
  },
  {
    name: "Suphalak",
    minWeight: "9",
    maxWeight: "12",
    activity: "low",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Suphalak_Female_in_Thailand_named_AumDaengManee.jpg/250px-Suphalak_Female_in_Thailand_named_AumDaengManee.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Suphalak",
  },
  {
    name: "Thai",
    minWeight: "7",
    maxWeight: "16",
    activity: "medium",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Thai",
  },
  {
    name: "Tiffany",
    minWeight: "6",
    maxWeight: "17",
    activity: "medium",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Tiffany",
  },
  {
    name: "Tonk",
    minWeight: "7",
    maxWeight: "11",
    activity: "high",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Tonk",
  },
  {
    name: "Toyger",
    minWeight: "10",
    maxWeight: "14",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Toyger_-_Cornish_Rex_presentation_show_Riihim%C3%A4ki_2008-11-16_IMG_0101.JPG/250px-Toyger_-_Cornish_Rex_presentation_show_Riihim%C3%A4ki_2008-11-16_IMG_0101.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Toyger",
  },
  {
    name: "Ukrainian Levkoy",
    minWeight: "8",
    maxWeight: "11",
    activity: "high",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Ukrainian_Levkoy_cat.jpg/250px-Ukrainian_Levkoy_cat.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Ukrainian_Levkoy",
  },
  {
    name: "York Chocolate",
    minWeight: "6",
    maxWeight: "18",
    activity: "high",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/York_Chocolate.jpg/250px-York_Chocolate.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/York_Chocolate",
  },
  {
    name: "Australian Mist",
    minWeight: "6",
    maxWeight: "14",
    activity: "low",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Australian_Mist.jpg/250px-Australian_Mist.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Australian_Mist",
  },
  {
    name: "Brazilian Shorthair",
    minWeight: "6",
    maxWeight: "16",
    activity: "medium",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Gato_pelo_curto_brasileiro.JPG/250px-Gato_pelo_curto_brasileiro.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Brazilian_Shorthair",
  },
  {
    name: "California Spangled",
    minWeight: "10",
    maxWeight: "12",
    activity: "medium",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Star_Spangled_Cat.jpg/250px-Star_Spangled_Cat.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/California_Spangled",
  },
  {
    name: "Chausie",
    minWeight: "5",
    maxWeight: "15",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image: "https://upload.wikimedia.org/wikipedia/commons/0/06/ChausieA.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Chausie",
  },
  {
    name: "Cheetoh",
    minWeight: "5",
    maxWeight: "13",
    activity: "low",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/Cheetoh",
  },
  {
    name: "Cyprus",
    minWeight: "10",
    maxWeight: "17",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/250px-Flag_of_Cyprus.svg.png",
    usefulLink: "https://en.wikipedia.org/wiki/Cyprus",
  },
  {
    name: "Dwelf",
    minWeight: "6",
    maxWeight: "19",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Dwelf",
  },
  {
    name: "Havana Brown",
    minWeight: "9",
    maxWeight: "14",
    activity: "low",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Havana_kittens.jpg/250px-Havana_kittens.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Havana_Brown",
  },
  {
    name: "Kinkalow",
    minWeight: "9",
    maxWeight: "20",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Kinkalow",
  },
  {
    name: "Lambkin",
    minWeight: "8",
    maxWeight: "11",
    activity: "high",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Lambkin",
  },
  {
    name: "Mekong Bobtail",
    minWeight: "5",
    maxWeight: "20",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Mekong_Bobtail",
  },
  {
    name: "Napoleon",
    minWeight: "5",
    maxWeight: "19",
    activity: "high",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project.jpg/250px-Jacques-Louis_David_-_The_Emperor_Napoleon_in_His_Study_at_the_Tuileries_-_Google_Art_Project.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Napoleon",
  },
  {
    name: "Oriental Bicolor",
    minWeight: "7",
    maxWeight: "12",
    activity: "high",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Oriental_shorthair_20070130_caroline.jpg/250px-Oriental_shorthair_20070130_caroline.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Oriental_Bicolor",
  },
  {
    name: "Raas",
    minWeight: "6",
    maxWeight: "16",
    activity: "high",
    price: "$$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Raas",
  },
  {
    name: "Ragdoll Variant",
    minWeight: "7",
    maxWeight: "13",
    activity: "high",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/Ragdoll_Variant",
  },
  {
    name: "Russian White",
    minWeight: "6",
    maxWeight: "11",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Russian_White",
  },
  {
    name: "Scottish Straight",
    minWeight: "10",
    maxWeight: "13",
    activity: "medium",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Black_Scottihs_Fold_Cat.png/250px-Black_Scottihs_Fold_Cat.png",
    usefulLink: "https://en.wikipedia.org/wiki/Scottish_Straight",
  },
  {
    name: "Tennessee Rex",
    minWeight: "7",
    maxWeight: "12",
    activity: "medium",
    price: "$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/Tennessee_Rex",
  },
  {
    name: "Texas Rex",
    minWeight: "7",
    maxWeight: "12",
    activity: "high",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/Texas_Rex",
  },
  {
    name: "Turkish Vankedisi",
    minWeight: "7",
    maxWeight: "12",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Red_Turkish_Van_Male_Tom.png/250px-Red_Turkish_Van_Male_Tom.png",
    usefulLink: "https://en.wikipedia.org/wiki/Turkish_Vankedisi",
  },
  {
    name: "York Rex",
    minWeight: "9",
    maxWeight: "13",
    activity: "low",
    price: "$$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/York_Rex",
  },
  {
    name: "German Rex",
    minWeight: "8",
    maxWeight: "18",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/German_rex_harry_%28cropped%29.jpg/250px-German_rex_harry_%28cropped%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/German_Rex",
  },
  {
    name: "Celtic Shorthair",
    minWeight: "9",
    maxWeight: "14",
    activity: "medium",
    price: "$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Female_European_shorthair_in_cat_show_Helsinki_2005-07-31.JPG/250px-Female_European_shorthair_in_cat_show_Helsinki_2005-07-31.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Celtic_Shorthair",
  },
  {
    name: "American Ringtail",
    minWeight: "9",
    maxWeight: "19",
    activity: "high",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/American_Ringtail",
  },
  {
    name: "Asian",
    minWeight: "9",
    maxWeight: "13",
    activity: "low",
    price: "$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Asian",
  },
  {
    name: "Asian Semi-longhair",
    minWeight: "10",
    maxWeight: "19",
    activity: "medium",
    price: "$$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Tiffanie_at_cat_show.jpg/250px-Tiffanie_at_cat_show.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Asian_Semi-longhair",
  },
  {
    name: "Bambino",
    minWeight: "6",
    maxWeight: "18",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Bambino",
  },
  {
    name: "Bristol",
    minWeight: "8",
    maxWeight: "15",
    activity: "medium",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Clifton_Suspension_Bridge_and_the_Observatory_in_Bristol%2C_England.jpg/330px-Clifton_Suspension_Bridge_and_the_Observatory_in_Bristol%2C_England.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bristol",
  },
  {
    name: "British Longhair",
    minWeight: "8",
    maxWeight: "14",
    activity: "low",
    price: "$$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: true,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Britishblue.jpg/250px-Britishblue.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/British_Longhair",
  },
  {
    name: "Cuban Cat",
    minWeight: "7",
    maxWeight: "13",
    activity: "medium",
    price: "$$$",
    sheds: "lot",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/Cuban_Cat",
  },
  {
    name: "Desert Lynx",
    minWeight: "7",
    maxWeight: "17",
    activity: "high",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "quiet",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Desert_Lynx",
  },
  {
    name: "Dwelf Variant",
    minWeight: "5",
    maxWeight: "17",
    activity: "low",
    price: "$",
    sheds: "none",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/Dwelf_Variant",
  },
  {
    name: "Himalayan Variant",
    minWeight: "7",
    maxWeight: "18",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "",
    barks: "",
    affectionate: false,
    talkative: "chatty",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/Himalayan_Variant",
  },
];
