export const dogs = [
  {
    name: "Labrador Retriever",
    minWeight: "58",
    maxWeight: "84",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "moderate",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Labrador_on_Quantock_%282175262184%29.jpg/250px-Labrador_on_Quantock_%282175262184%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Labrador_Retriever",
  },
  {
    name: "German Shepherd",
    minWeight: "30",
    maxWeight: "111",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "easy",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/German_Shepherd_-_DSC_0346_%2810096362833%29.jpg/250px-German_Shepherd_-_DSC_0346_%2810096362833%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/German_Shepherd",
  },
  {
    name: "Golden Retriever",
    minWeight: "52",
    maxWeight: "82",
    activity: "medium",
    price: "$$$",
    sheds: "little",
    trainability: "moderate",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Golden_Retriever_Dukedestiny01_drvd.jpg/250px-Golden_Retriever_Dukedestiny01_drvd.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Golden_Retriever",
  },
  {
    name: "Bulldog",
    minWeight: "41",
    maxWeight: "120",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "easy",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Bulldog_inglese.jpg/250px-Bulldog_inglese.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bulldog",
  },
  {
    name: "Poodle",
    minWeight: "59",
    maxWeight: "96",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "easy",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Full_attention_%288067543690%29.jpg/250px-Full_attention_%288067543690%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Poodle",
  },
  {
    name: "Beagle",
    minWeight: "25",
    maxWeight: "100",
    activity: "low",
    price: "$$$",
    sheds: "little",
    trainability: "difficult",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Beagle_600.jpg/250px-Beagle_600.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Beagle",
  },
  {
    name: "Rottweiler",
    minWeight: "21",
    maxWeight: "108",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "difficult",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Rottweiler_standing_facing_left.jpg/250px-Rottweiler_standing_facing_left.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Rottweiler",
  },
  {
    name: "German Shorthaired Pointer",
    minWeight: "26",
    maxWeight: "84",
    activity: "high",
    price: "$$",
    sheds: "lot",
    trainability: "difficult",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Duitse_staande_korthaar_10-10-2.jpg/250px-Duitse_staande_korthaar_10-10-2.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/German_Shorthaired_Pointer",
  },
  {
    name: "Yorkshire Terrier",
    minWeight: "32",
    maxWeight: "95",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "moderate",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/%282_version%29_Grupp_3%2C_YORKSHIRETERRIER%2C_NO_UCH_SE_UCH_Oxzar_Amazing_Bel%E2%80%99s_Toffy_%2824310212305%29.jpg/250px-%282_version%29_Grupp_3%2C_YORKSHIRETERRIER%2C_NO_UCH_SE_UCH_Oxzar_Amazing_Bel%E2%80%99s_Toffy_%2824310212305%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Yorkshire_Terrier",
  },
  {
    name: "Boxer",
    minWeight: "53",
    maxWeight: "109",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "difficult",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Boxer",
  },
  {
    name: "Dachshund",
    minWeight: "43",
    maxWeight: "72",
    activity: "medium",
    price: "$$",
    sheds: "little",
    trainability: "difficult",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/%EB%8B%A5%EC%8A%A4%ED%9B%88%ED%8A%B8%28%EB%8B%A8%EB%AA%A8%EC%A2%85%29_%28Dachshund_%28Short%29%29.jpg/250px-%EB%8B%A5%EC%8A%A4%ED%9B%88%ED%8A%B8%28%EB%8B%A8%EB%AA%A8%EC%A2%85%29_%28Dachshund_%28Short%29%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Dachshund",
  },
  {
    name: "Pembroke Welsh Corgi",
    minWeight: "28",
    maxWeight: "61",
    activity: "low",
    price: "$$",
    sheds: "little",
    trainability: "moderate",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Welsh_Pembroke_Corgi.jpg/250px-Welsh_Pembroke_Corgi.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Pembroke_Welsh_Corgi",
  },
  {
    name: "Siberian Husky",
    minWeight: "39",
    maxWeight: "76",
    activity: "medium",
    price: "$$",
    sheds: "lot",
    trainability: "moderate",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Husky_L.jpg/250px-Husky_L.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Siberian_Husky",
  },
  {
    name: "Australian Shepherd",
    minWeight: "42",
    maxWeight: "83",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "easy",
    barks: "medium",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Australian_Shepherd_red_bi.JPG/250px-Australian_Shepherd_red_bi.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Australian_Shepherd",
  },
  {
    name: "Great Dane",
    minWeight: "22",
    maxWeight: "88",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "easy",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Dog_niemiecki_%C5%BC%C3%B3%C5%82ty_LM980.jpg/250px-Dog_niemiecki_%C5%BC%C3%B3%C5%82ty_LM980.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Great_Dane",
  },
  {
    name: "Doberman Pinscher",
    minWeight: "47",
    maxWeight: "64",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "difficult",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Dobermann_handling.jpg/250px-Dobermann_handling.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Doberman_Pinscher",
  },
  {
    name: "Cavalier King Charles Spaniel",
    minWeight: "24",
    maxWeight: "92",
    activity: "high",
    price: "$",
    sheds: "little",
    trainability: "moderate",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/CarterBIS.Tiki.13.6.09.jpg/250px-CarterBIS.Tiki.13.6.09.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Cavalier_King_Charles_Spaniel",
  },
  {
    name: "Miniature Schnauzer",
    minWeight: "58",
    maxWeight: "100",
    activity: "low",
    price: "$$$",
    sheds: "little",
    trainability: "easy",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/%D0%A6%D0%B2%D0%B5%D1%80%D0%B3%D1%88%D0%BD%D0%B0%D1%83%D1%86%D0%B5%D1%80_%D0%BE%D0%BA%D1%80%D0%B0%D1%81_%D1%87%D0%B5%D1%80%D0%BD%D1%8B%D0%B9_%D1%81_%D1%81%D0%B5%D1%80%D0%B5%D0%B1%D1%80%D0%BE%D0%BC.JPG/330px-%D0%A6%D0%B2%D0%B5%D1%80%D0%B3%D1%88%D0%BD%D0%B0%D1%83%D1%86%D0%B5%D1%80_%D0%BE%D0%BA%D1%80%D0%B0%D1%81_%D1%87%D0%B5%D1%80%D0%BD%D1%8B%D0%B9_%D1%81_%D1%81%D0%B5%D1%80%D0%B5%D0%B1%D1%80%D0%BE%D0%BC.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Miniature_Schnauzer",
  },
  {
    name: "Shih Tzu",
    minWeight: "57",
    maxWeight: "67",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "moderate",
    barks: "medium",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Shihtzu_%28cropped%29.jpg/250px-Shihtzu_%28cropped%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Shih_Tzu",
  },
  {
    name: "Boston Terrier",
    minWeight: "40",
    maxWeight: "79",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "difficult",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Boston-terrier-carlos-de.JPG/250px-Boston-terrier-carlos-de.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Boston_Terrier",
  },
  {
    name: "Bernese Mountain Dog",
    minWeight: "59",
    maxWeight: "65",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "moderate",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Standing_Bernese_Mountain_Dog_Female_%28cropped%29.jpg/250px-Standing_Bernese_Mountain_Dog_Female_%28cropped%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bernese_Mountain_Dog",
  },
  {
    name: "Pomeranian",
    minWeight: "49",
    maxWeight: "82",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "easy",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Pomeranian",
  },
  {
    name: "Havanese",
    minWeight: "23",
    maxWeight: "119",
    activity: "low",
    price: "$$$",
    sheds: "little",
    trainability: "easy",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/DJI_0197_crp_wiki.jpg/330px-DJI_0197_crp_wiki.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Havanese",
  },
  {
    name: "Shetland Sheepdog",
    minWeight: "21",
    maxWeight: "111",
    activity: "medium",
    price: "$$",
    sheds: "none",
    trainability: "moderate",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Shetland_Sheepdog_sable.jpg/250px-Shetland_Sheepdog_sable.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Shetland_Sheepdog",
  },
  {
    name: "Brittany",
    minWeight: "44",
    maxWeight: "82",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "easy",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Satellite_picture_of_Brittany_-_NASA%2C_2002.jpg/250px-Satellite_picture_of_Brittany_-_NASA%2C_2002.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Brittany",
  },
  {
    name: "English Springer Spaniel",
    minWeight: "29",
    maxWeight: "77",
    activity: "high",
    price: "$$$",
    sheds: "lot",
    trainability: "difficult",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Springer_Spaniel_Wide_Shot.jpg/250px-Springer_Spaniel_Wide_Shot.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/English_Springer_Spaniel",
  },
  {
    name: "Cocker Spaniel",
    minWeight: "29",
    maxWeight: "87",
    activity: "medium",
    price: "$",
    sheds: "lot",
    trainability: "moderate",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Cocker_Spaniel",
  },
  {
    name: "Vizsla",
    minWeight: "54",
    maxWeight: "91",
    activity: "high",
    price: "$$",
    sheds: "none",
    trainability: "easy",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Wy%C5%BCe%C5%82_w%C4%99gierski_g%C5%82adkow%C5%82osy_500.jpg/250px-Wy%C5%BCe%C5%82_w%C4%99gierski_g%C5%82adkow%C5%82osy_500.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Vizsla",
  },
  {
    name: "Cane Corso",
    minWeight: "35",
    maxWeight: "75",
    activity: "high",
    price: "$$$",
    sheds: "none",
    trainability: "easy",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Cane_corso_temi_1_1024x768x24_%28cropped%29.png/250px-Cane_corso_temi_1_1024x768x24_%28cropped%29.png",
    usefulLink: "https://en.wikipedia.org/wiki/Cane_Corso",
  },
  {
    name: "Mastiff",
    minWeight: "42",
    maxWeight: "107",
    activity: "high",
    price: "$",
    sheds: "lot",
    trainability: "easy",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Mastiff",
  },
  {
    name: "Chihuahua",
    minWeight: "32",
    maxWeight: "70",
    activity: "medium",
    price: "$$",
    sheds: "lot",
    trainability: "moderate",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Chihuahua",
  },
  {
    name: "Weimaraner",
    minWeight: "54",
    maxWeight: "102",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "easy",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Weimaraner_Freika-2.jpg/250px-Weimaraner_Freika-2.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Weimaraner",
  },
  {
    name: "Newfoundland",
    minWeight: "45",
    maxWeight: "113",
    activity: "medium",
    price: "$$$",
    sheds: "little",
    trainability: "difficult",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Newfoundland_and_Labrador.svg/250px-Flag_of_Newfoundland_and_Labrador.svg.png",
    usefulLink: "https://en.wikipedia.org/wiki/Newfoundland",
  },
  {
    name: "Border Collie",
    minWeight: "53",
    maxWeight: "119",
    activity: "low",
    price: "$$$",
    sheds: "none",
    trainability: "easy",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Border_Collie_600.jpg/250px-Border_Collie_600.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Border_Collie",
  },
  {
    name: "Basset Hound",
    minWeight: "48",
    maxWeight: "118",
    activity: "high",
    price: "$",
    sheds: "lot",
    trainability: "easy",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/BassetHound_profil.jpg/250px-BassetHound_profil.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Basset_Hound",
  },
  {
    name: "Rhodesian Ridgeback",
    minWeight: "30",
    maxWeight: "91",
    activity: "high",
    price: "$$$",
    sheds: "lot",
    trainability: "easy",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Rhodesian_ridgeback.jpg/250px-Rhodesian_ridgeback.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Rhodesian_Ridgeback",
  },
  {
    name: "West Highland White Terrier",
    minWeight: "52",
    maxWeight: "94",
    activity: "medium",
    price: "$$",
    sheds: "lot",
    trainability: "easy",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/West_Highland_White_Terrier_Krakow.jpg/250px-West_Highland_White_Terrier_Krakow.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/West_Highland_White_Terrier",
  },
  {
    name: "Belgian Malinois",
    minWeight: "26",
    maxWeight: "74",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "easy",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/04_-_Belgian_shepherd_dog_varieties_-_Groenendael%2CTervuren%2C_Malinois%2C_Laekenois.jpg/250px-04_-_Belgian_shepherd_dog_varieties_-_Groenendael%2CTervuren%2C_Malinois%2C_Laekenois.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Belgian_Malinois",
  },
  {
    name: "Collie",
    minWeight: "41",
    maxWeight: "77",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "difficult",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/1Dog-rough-collie-portrait.jpg/250px-1Dog-rough-collie-portrait.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Collie",
  },
  {
    name: "Papillon",
    minWeight: "22",
    maxWeight: "98",
    activity: "high",
    price: "$$",
    sheds: "little",
    trainability: "difficult",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Papillon",
  },
  {
    name: "Bichon Frise",
    minWeight: "58",
    maxWeight: "103",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "easy",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Bichon_Fris%C3%A9_-_studdogbichon.jpg/250px-Bichon_Fris%C3%A9_-_studdogbichon.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bichon_Frise",
  },
  {
    name: "Akita",
    minWeight: "39",
    maxWeight: "94",
    activity: "high",
    price: "$$$",
    sheds: "none",
    trainability: "easy",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Akita",
  },
  {
    name: "St. Bernard",
    minWeight: "35",
    maxWeight: "89",
    activity: "high",
    price: "$",
    sheds: "lot",
    trainability: "easy",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/St._Bernard",
  },
  {
    name: "Bullmastiff",
    minWeight: "38",
    maxWeight: "77",
    activity: "medium",
    price: "$$",
    sheds: "none",
    trainability: "difficult",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Bullmastiff_edited.JPG/250px-Bullmastiff_edited.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Bullmastiff",
  },
  {
    name: "Soft Coated Wheaten Terrier",
    minWeight: "28",
    maxWeight: "76",
    activity: "low",
    price: "$$$",
    sheds: "none",
    trainability: "moderate",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Soft-Coated_Wheaten_Terrier.jpg/250px-Soft-Coated_Wheaten_Terrier.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Soft_Coated_Wheaten_Terrier",
  },
  {
    name: "Bloodhound",
    minWeight: "41",
    maxWeight: "93",
    activity: "medium",
    price: "$$",
    sheds: "lot",
    trainability: "moderate",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Bloodhound_Erland22.jpg/250px-Bloodhound_Erland22.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bloodhound",
  },
  {
    name: "Chesapeake Bay Retriever",
    minWeight: "44",
    maxWeight: "64",
    activity: "high",
    price: "$$$",
    sheds: "none",
    trainability: "easy",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/CH_Chesapeake.jpg/250px-CH_Chesapeake.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Chesapeake_Bay_Retriever",
  },
  {
    name: "Airedale Terrier",
    minWeight: "29",
    maxWeight: "83",
    activity: "medium",
    price: "$$",
    sheds: "none",
    trainability: "easy",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/52/Airedale_Terrier.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Airedale_Terrier",
  },
  {
    name: "Alaskan Malamute",
    minWeight: "20",
    maxWeight: "92",
    activity: "high",
    price: "$$$",
    sheds: "little",
    trainability: "moderate",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Alaskan_Malamute.jpg/250px-Alaskan_Malamute.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Alaskan_Malamute",
  },
  {
    name: "Dalmatian",
    minWeight: "54",
    maxWeight: "114",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "easy",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Dalmatian",
  },
  {
    name: "Scottish Terrier",
    minWeight: "20",
    maxWeight: "67",
    activity: "high",
    price: "$$$",
    sheds: "none",
    trainability: "moderate",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Scottish_Terrier_Photo_of_Face.jpg/250px-Scottish_Terrier_Photo_of_Face.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Scottish_Terrier",
  },
  {
    name: "Whippet",
    minWeight: "27",
    maxWeight: "116",
    activity: "low",
    price: "$$",
    sheds: "lot",
    trainability: "moderate",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Whippet_2018_6.jpg/250px-Whippet_2018_6.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Whippet",
  },
  {
    name: "Chinese Shar-Pei",
    minWeight: "33",
    maxWeight: "68",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "moderate",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Adult_sharpei.jpg/250px-Adult_sharpei.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Chinese_Shar-Pei",
  },
  {
    name: "Lhasa Apso",
    minWeight: "40",
    maxWeight: "72",
    activity: "low",
    price: "$",
    sheds: "little",
    trainability: "easy",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Aishia.jpg/250px-Aishia.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Lhasa_Apso",
  },
  {
    name: "Samoyed",
    minWeight: "34",
    maxWeight: "100",
    activity: "low",
    price: "$",
    sheds: "none",
    trainability: "moderate",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Samoyed",
  },
  {
    name: "Australian Cattle Dog",
    minWeight: "45",
    maxWeight: "97",
    activity: "high",
    price: "$$",
    sheds: "lot",
    trainability: "moderate",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/ACD-blue-spud.jpg/250px-ACD-blue-spud.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Australian_Cattle_Dog",
  },
  {
    name: "Cairn Terrier",
    minWeight: "21",
    maxWeight: "64",
    activity: "high",
    price: "$$$",
    sheds: "little",
    trainability: "easy",
    barks: "medium",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Cairn-Terrier-Garten1.jpg/250px-Cairn-Terrier-Garten1.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Cairn_Terrier",
  },
  {
    name: "Basenji",
    minWeight: "48",
    maxWeight: "61",
    activity: "medium",
    price: "$",
    sheds: "lot",
    trainability: "easy",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Basenji_Profile_%28loosercrop%29.jpg/250px-Basenji_Profile_%28loosercrop%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Basenji",
  },
  {
    name: "Wirehaired Pointing Griffon",
    minWeight: "24",
    maxWeight: "111",
    activity: "low",
    price: "$$",
    sheds: "little",
    trainability: "moderate",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/GCH_Int_Ch_UCH_Zerubbabel_von_Herrenhausen_CGC_MHA.jpg/250px-GCH_Int_Ch_UCH_Zerubbabel_von_Herrenhausen_CGC_MHA.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Wirehaired_Pointing_Griffon",
  },
  {
    name: "Shiba Inu",
    minWeight: "24",
    maxWeight: "67",
    activity: "medium",
    price: "$$",
    sheds: "lot",
    trainability: "easy",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Taka_Shiba.jpg/250px-Taka_Shiba.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Shiba_Inu",
  },
  {
    name: "Irish Setter",
    minWeight: "59",
    maxWeight: "120",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "moderate",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Can_Setter_dog_GFDL.jpg/250px-Can_Setter_dog_GFDL.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Irish_Setter",
  },
  {
    name: "Old English Sheepdog",
    minWeight: "50",
    maxWeight: "65",
    activity: "high",
    price: "$$",
    sheds: "little",
    trainability: "moderate",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Old_English_Sheepdog_%28side%29.jpg/250px-Old_English_Sheepdog_%28side%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Old_English_Sheepdog",
  },
  {
    name: "Great Pyrenees",
    minWeight: "28",
    maxWeight: "85",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "easy",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Great_Pyrenees_Mountain_Dog_2.png/250px-Great_Pyrenees_Mountain_Dog_2.png",
    usefulLink: "https://en.wikipedia.org/wiki/Great_Pyrenees",
  },
  {
    name: "Anatolian Shepherd Dog",
    minWeight: "43",
    maxWeight: "67",
    activity: "high",
    price: "$$$",
    sheds: "lot",
    trainability: "moderate",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Kangal_front_on.jpg/250px-Kangal_front_on.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Anatolian_Shepherd_Dog",
  },
  {
    name: "Keeshond",
    minWeight: "54",
    maxWeight: "101",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "moderate",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Keeshond_Majic_standing_cropped.jpg/250px-Keeshond_Majic_standing_cropped.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Keeshond",
  },
  {
    name: "American Eskimo Dog",
    minWeight: "43",
    maxWeight: "69",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "difficult",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/American_Eskimo_Dog_1.jpg/250px-American_Eskimo_Dog_1.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/American_Eskimo_Dog",
  },
  {
    name: "Chinese Crested",
    minWeight: "33",
    maxWeight: "94",
    activity: "medium",
    price: "$$$",
    sheds: "none",
    trainability: "moderate",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/IndyStands.jpg/250px-IndyStands.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Chinese_Crested",
  },
  {
    name: "Norwegian Elkhound",
    minWeight: "30",
    maxWeight: "104",
    activity: "medium",
    price: "$$$",
    sheds: "little",
    trainability: "easy",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Elkhound2020_%28cropped%29.jpg/250px-Elkhound2020_%28cropped%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Norwegian_Elkhound",
  },
  {
    name: "Miniature Pinscher",
    minWeight: "28",
    maxWeight: "62",
    activity: "high",
    price: "$$",
    sheds: "none",
    trainability: "moderate",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Miniature_pinscher.jpg/250px-Miniature_pinscher.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Miniature_Pinscher",
  },
  {
    name: "Italian Greyhound",
    minWeight: "26",
    maxWeight: "98",
    activity: "high",
    price: "$",
    sheds: "lot",
    trainability: "moderate",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Italian_Greyhound_standing_gray_%28cropped%29.jpg/250px-Italian_Greyhound_standing_gray_%28cropped%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Italian_Greyhound",
  },
  {
    name: "Japanese Chin",
    minWeight: "38",
    maxWeight: "90",
    activity: "medium",
    price: "$$$",
    sheds: "lot",
    trainability: "easy",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Chin_posing.jpg/250px-Chin_posing.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Japanese_Chin",
  },
  {
    name: "Brussels Griffon",
    minWeight: "33",
    maxWeight: "86",
    activity: "high",
    price: "$$",
    sheds: "little",
    trainability: "easy",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Monkey_Bizniz_Drama_Queen.jpg/250px-Monkey_Bizniz_Drama_Queen.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Brussels_Griffon",
  },
  {
    name: "Toy Fox Terrier",
    minWeight: "46",
    maxWeight: "76",
    activity: "medium",
    price: "$",
    sheds: "lot",
    trainability: "moderate",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Toy_Fox_Terrier_2.jpg/250px-Toy_Fox_Terrier_2.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Toy_Fox_Terrier",
  },
  {
    name: "Tibetan Terrier",
    minWeight: "27",
    maxWeight: "64",
    activity: "low",
    price: "$",
    sheds: "none",
    trainability: "moderate",
    barks: "medium",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Tibet_Terrier_Bennie_%28cropped%29.jpg/250px-Tibet_Terrier_Bennie_%28cropped%29.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Tibetan_Terrier",
  },
  {
    name: "Manchester Terrier",
    minWeight: "47",
    maxWeight: "77",
    activity: "high",
    price: "$$$",
    sheds: "little",
    trainability: "difficult",
    barks: "medium",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Mancherster_Terrier.jpg/250px-Mancherster_Terrier.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Manchester_Terrier",
  },
  {
    name: "Norwich Terrier",
    minWeight: "21",
    maxWeight: "80",
    activity: "medium",
    price: "$",
    sheds: "lot",
    trainability: "moderate",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Norwichterrier.jpg/250px-Norwichterrier.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Norwich_Terrier",
  },
  {
    name: "Irish Wolfhound",
    minWeight: "45",
    maxWeight: "64",
    activity: "low",
    price: "$$",
    sheds: "lot",
    trainability: "moderate",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/%282%29_Irish_Wolfhound_4.jpg/250px-%282%29_Irish_Wolfhound_4.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Irish_Wolfhound",
  },
  {
    name: "Nova Scotia Duck Tolling Retriever",
    minWeight: "54",
    maxWeight: "64",
    activity: "medium",
    price: "$$",
    sheds: "little",
    trainability: "difficult",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Duck_Toller.jpg/250px-Duck_Toller.jpg",
    usefulLink:
      "https://en.wikipedia.org/wiki/Nova_Scotia_Duck_Tolling_Retriever",
  },
  {
    name: "Afghan Hound",
    minWeight: "47",
    maxWeight: "75",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "difficult",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Afghan_dog_-_cropped.jpg/250px-Afghan_dog_-_cropped.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Afghan_Hound",
  },
  {
    name: "Leonberger",
    minWeight: "23",
    maxWeight: "62",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "easy",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Leonberger_male.jpg/250px-Leonberger_male.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Leonberger",
  },
  {
    name: "Giant Schnauzer",
    minWeight: "59",
    maxWeight: "68",
    activity: "high",
    price: "$$",
    sheds: "none",
    trainability: "moderate",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Nev_Lemar_Barbara1.jpg/250px-Nev_Lemar_Barbara1.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Giant_Schnauzer",
  },
  {
    name: "Standard Schnauzer",
    minWeight: "23",
    maxWeight: "114",
    activity: "low",
    price: "$$",
    sheds: "none",
    trainability: "difficult",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Standard_Grey_Schnauzer_%28cropped%29.JPG/250px-Standard_Grey_Schnauzer_%28cropped%29.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Standard_Schnauzer",
  },
  {
    name: "Tibetan Spaniel",
    minWeight: "23",
    maxWeight: "94",
    activity: "low",
    price: "$$$",
    sheds: "little",
    trainability: "difficult",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tibetansk_spaniel.jpg/250px-Tibetansk_spaniel.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Tibetan_Spaniel",
  },
  {
    name: "English Toy Spaniel",
    minWeight: "23",
    maxWeight: "93",
    activity: "high",
    price: "$",
    sheds: "none",
    trainability: "moderate",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/King_Charles_Spaniel_200.jpg/250px-King_Charles_Spaniel_200.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/English_Toy_Spaniel",
  },
  {
    name: "Pekingese",
    minWeight: "39",
    maxWeight: "76",
    activity: "high",
    price: "$",
    sheds: "little",
    trainability: "moderate",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/1AKC_Pekingese_Dog_Show_2011.jpg/250px-1AKC_Pekingese_Dog_Show_2011.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Pekingese",
  },
  {
    name: "Saluki",
    minWeight: "54",
    maxWeight: "112",
    activity: "medium",
    price: "$",
    sheds: "lot",
    trainability: "easy",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Red_Smooth_Saluki.jpg/250px-Red_Smooth_Saluki.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Saluki",
  },
  {
    name: "Borzois",
    minWeight: "39",
    maxWeight: "105",
    activity: "medium",
    price: "$",
    sheds: "none",
    trainability: "easy",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image: "/default.png",
    usefulLink: "https://en.wikipedia.org/wiki/Borzois",
  },
  {
    name: "American Staffordshire Terrier",
    minWeight: "57",
    maxWeight: "104",
    activity: "high",
    price: "$$",
    sheds: "lot",
    trainability: "easy",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/AMERICAN_STAFFORDSHIRE_TERRIER%2C_Zican%E2%80%99s_Bz_Ez_Dragon_%2824208348891%29.2.jpg/250px-AMERICAN_STAFFORDSHIRE_TERRIER%2C_Zican%E2%80%99s_Bz_Ez_Dragon_%2824208348891%29.2.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/American_Staffordshire_Terrier",
  },
  {
    name: "Plott",
    minWeight: "45",
    maxWeight: "99",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "difficult",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Plotthund_Kynnagardens_Ziggy_Lundamo.JPG/250px-Plotthund_Kynnagardens_Ziggy_Lundamo.JPG",
    usefulLink: "https://en.wikipedia.org/wiki/Plott",
  },
  {
    name: "Kuvasz",
    minWeight: "37",
    maxWeight: "74",
    activity: "high",
    price: "$",
    sheds: "little",
    trainability: "difficult",
    barks: "high",
    affectionate: false,
    talkative: "",
    grooming: "high",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Kuvasz_named_Kan.jpg/250px-Kuvasz_named_Kan.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Kuvasz",
  },
  {
    name: "Komondor",
    minWeight: "26",
    maxWeight: "69",
    activity: "low",
    price: "$$",
    sheds: "lot",
    trainability: "easy",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "low",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Komondor_delvin.jpg/250px-Komondor_delvin.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Komondor",
  },
  {
    name: "Boykin Spaniel",
    minWeight: "48",
    maxWeight: "106",
    activity: "low",
    price: "$$",
    sheds: "none",
    trainability: "difficult",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Boykin_Spaniel_April_Jet.jpg/250px-Boykin_Spaniel_April_Jet.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Boykin_Spaniel",
  },
  {
    name: "Belgian Tervuren",
    minWeight: "26",
    maxWeight: "120",
    activity: "high",
    price: "$$$",
    sheds: "lot",
    trainability: "easy",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/04_-_Belgian_shepherd_dog_varieties_-_Groenendael%2CTervuren%2C_Malinois%2C_Laekenois.jpg/250px-04_-_Belgian_shepherd_dog_varieties_-_Groenendael%2CTervuren%2C_Malinois%2C_Laekenois.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Belgian_Tervuren",
  },
  {
    name: "Bergamasco Sheepdog",
    minWeight: "37",
    maxWeight: "64",
    activity: "low",
    price: "$$$",
    sheds: "lot",
    trainability: "difficult",
    barks: "low",
    affectionate: false,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Ortensia_di_Valle_Scrivia.jpg/250px-Ortensia_di_Valle_Scrivia.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bergamasco_Sheepdog",
  },
  {
    name: "Bearded Collie",
    minWeight: "26",
    maxWeight: "86",
    activity: "medium",
    price: "$",
    sheds: "little",
    trainability: "difficult",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Bearded_Collie_600.jpg/250px-Bearded_Collie_600.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bearded_Collie",
  },
  {
    name: "Belgian Sheepdog",
    minWeight: "29",
    maxWeight: "76",
    activity: "low",
    price: "$",
    sheds: "lot",
    trainability: "difficult",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "high",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/04_-_Belgian_shepherd_dog_varieties_-_Groenendael%2CTervuren%2C_Malinois%2C_Laekenois.jpg/250px-04_-_Belgian_shepherd_dog_varieties_-_Groenendael%2CTervuren%2C_Malinois%2C_Laekenois.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Belgian_Sheepdog",
  },
  {
    name: "American Foxhound",
    minWeight: "40",
    maxWeight: "105",
    activity: "high",
    price: "$$$",
    sheds: "none",
    trainability: "difficult",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/AmericanFoxhound2.jpg/250px-AmericanFoxhound2.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/American_Foxhound",
  },
  {
    name: "Bluetick Coonhound",
    minWeight: "32",
    maxWeight: "80",
    activity: "low",
    price: "$$$",
    sheds: "none",
    trainability: "difficult",
    barks: "low",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: false,
    kidFriendly: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/BluetickCoonhound.jpg/250px-BluetickCoonhound.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/Bluetick_Coonhound",
  },
  {
    name: "English Foxhound",
    minWeight: "31",
    maxWeight: "99",
    activity: "high",
    price: "$",
    sheds: "little",
    trainability: "moderate",
    barks: "high",
    affectionate: true,
    talkative: "",
    grooming: "low",
    hypoallergenic: false,
    kidFriendly: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/English_Foxhound_portrait.jpg/250px-English_Foxhound_portrait.jpg",
    usefulLink: "https://en.wikipedia.org/wiki/English_Foxhound",
  },
  {
    name: "Harrier",
    minWeight: "54",
    maxWeight: "77",
    activity: "high",
    price: "$",
    sheds: "little",
    trainability: "easy",
    barks: "medium",
    affectionate: true,
    talkative: "",
    grooming: "medium",
    hypoallergenic: true,
    kidFriendly: false,
    image: "",
    usefulLink: "https://en.wikipedia.org/wiki/Harrier",
  },
];
